care-australia-uat/force-app/main/default/objects/Stripe_Setting__c/Stripe_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To handle settings for stripe integration</description>
    <label>Stripe Setting</label>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Stripe_Setting__c/fields/Activation__c.field-meta.xml
<CustomField>
    <fullName>Activation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activation</label>
    <type>Checkbox</type>
</CustomField>

care-australia-uat/force-app/main/default/classes/StripeWebhookProduct.cls
@RestResource(urlMapping='/api/webhooks/productapi')
global class StripeWebhookProduct {
	@HttpPost
    global static void handleProduct(){
        // Get's the data from stripe to salesforce (contact object)
     	try{
            if(Stripe_Setting__c.getInstance('Default').Activation__c){
                RestRequest request = RestContext.request;
                RestResponse response = RestContext.response;
                
                Campaign camp = new campaign();
                String requestBody=request.requestBody.toString();
                
                StripeProductWrapper wrapperResponse = StripeProductWrapper.parse(requestBody);
                
                camp.Stripe_Product_Id__c = wrapperResponse.data.object_z.id;
                camp.id = wrapperResponse.data.object_z.metadata.sf_campaign_id;
                camp.Name = wrapperResponse.data.object_z.name;
                camp.IsActive = wrapperResponse.data.object_z.active;
                
                if(String.isEmpty(wrapperResponse.data.object_z.metadata.sf_campaign_id)){
                    upsert camp Stripe_Product_Id__c;    
                }
                else{
                    upsert camp id;
                }
            }   
        }
        catch(Exception e){
            system.debug(e);
        }   
    }
}