care-australia-uat/force-app/main/default/objects/Donation_Bridge_Settings__c/Donation_Bridge_Settings__c.object-meta.xml
<CustomObject>
    <description>Holds the settings for the Donation Bridge</description>
    <label>Donation Bridge Settings</label>
    <nameField>
        <label>Donation Bridge Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donation Bridge Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Donation_Bridge_Settings__c/fields/End_User_Message__c.field-meta.xml
<CustomField>
    <fullName>End_User_Message__c</fullName>
    <label>End User Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Donation_Bridge_Settings__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <inlineHelpText>i.e. 1.0.1</inlineHelpText>
    <label>Version</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

care-australia-uat/force-app/main/default/classes/NBHeartbeat.cls
@RestResource(urlMapping='/NBHeartbeat/*')
global with sharing class NBHeartbeat {
    
    /**
     * The Heartbeat endpoing indicates to the Donation Bridge the status and version of the integration. A message can be sent to display to the user by setting System.Label.NBMessage.
     * Gordon Jackson October 2021 gordon@gordonjackson.org
     */
 	@HttpGet
    global static void doGet() {
        String versionNo = '';
        String message = '';
        List<Donation_Bridge_Settings__c> donationBridgeSettings = [ SELECT Version__c, End_user_Message__c from Donation_Bridge_Settings__c WHERE Active__c = true ];
        for (Donation_Bridge_Settings__c donationBridgeSetting : donationBridgeSettings) {
            if (donationBridgeSetting.Version__c == 'MESSAGE') {
                message = donationBridgeSetting.End_user_Message__c;
                versionNo = message;
            }
            else {
                versionNo = donationBridgeSetting.Version__c;
            }
            break;
        }
        RestContext.response.addHeader('Content-Type', 'application/json');
		RestContext.response.responseBody = Blob.valueOf('{ "version" : "' + versionNo + '", "build" : "a", "message" : "' + message + '" }');
    }
}