care-australia-uat/force-app/main/default/objects/Charge__c/Charge__c.object-meta.xml
<CustomObject>
    <description>Used to store charge coming from Stripe. The charge object will use in batch to update the respective Payment record.</description>
    <label>Charge</label>
    <nameField>
        <displayFormat>Ch-{00000000}</displayFormat>
        <label>Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Account_BSB__c.field-meta.xml
<CustomField>
    <fullName>Account_BSB__c</fullName>
    <label>Account BSB</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Account_Last_Digits__c.field-meta.xml
<CustomField>
    <fullName>Account_Last_Digits__c</fullName>
    <label>Account Last Digits</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Account_Token__c.field-meta.xml
<CustomField>
    <fullName>Account_Token__c</fullName>
    <label>Account Token</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Card_Expiration_Month__c.field-meta.xml
<CustomField>
    <fullName>Card_Expiration_Month__c</fullName>
    <label>Card Expiration Month</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Card_Expiration_Year__c.field-meta.xml
<CustomField>
    <fullName>Card_Expiration_Year__c</fullName>
    <label>Card Expiration Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Card_Last_Digits__c.field-meta.xml
<CustomField>
    <fullName>Card_Last_Digits__c</fullName>
    <label>Card Last Digits</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Card_Token__c.field-meta.xml
<CustomField>
    <fullName>Card_Token__c</fullName>
    <label>Card Token</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Donation_Source__c.field-meta.xml
<CustomField>
    <fullName>Donation_Source__c</fullName>
    <label>Donation Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Failure_Code__c.field-meta.xml
<CustomField>
    <fullName>Failure_Code__c</fullName>
    <label>Failure Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Is_Processed__c.field-meta.xml
<CustomField>
    <fullName>Is_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Will determine if the batch has been run successfully for the particular record</description>
    <label>Is Processed</label>
    <type>Checkbox</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Is_Recurring__c.field-meta.xml
<CustomField>
    <fullName>Is_Recurring__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Recurring</label>
    <type>Checkbox</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Opportunity_Id__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Id__c</fullName>
    <description>Opportunity Id from Charge object, inserted from sequence shift on Stripe</description>
    <label>Opportunity Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Outcome_Reason__c.field-meta.xml
<CustomField>
    <fullName>Outcome_Reason__c</fullName>
    <label>Outcome Reason</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Payment_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Created_Date__c</fullName>
    <label>Payment Created Date</label>
    <type>Date</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/RD_Installment_Day_Of_Month__c.field-meta.xml
<CustomField>
    <fullName>RD_Installment_Day_Of_Month__c</fullName>
    <label>RD Installment Day Of Month</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/RD_Installment_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>RD_Installment_Effective_Date__c</fullName>
    <label>RD Installment Effective Date</label>
    <type>Date</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/RD_Installment_Every__c.field-meta.xml
<CustomField>
    <fullName>RD_Installment_Every__c</fullName>
    <description>RD installment period for every month</description>
    <label>RD Installment Every</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/RD_Installment_Period__c.field-meta.xml
<CustomField>
    <fullName>RD_Installment_Period__c</fullName>
    <description>RD installment period</description>
    <label>RD Installment Period</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Recurring_Donation_Id__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Donation_Id__c</fullName>
    <description>Recurring Donation Id from Charge object, coming from Sequence Shift</description>
    <label>Recurring Donation Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Stripe_Charge_Amount__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Charge_Amount__c</fullName>
    <label>Stripe Charge Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Stripe_Charge_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Charge_Id__c</fullName>
    <description>External id of Charge, coming from Charge webhook response</description>
    <externalId>true</externalId>
    <label>Stripe Charge Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Stripe_Charge_Status__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Charge_Status__c</fullName>
    <description>Status of a Charge</description>
    <label>Stripe Charge Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>failed</fullName>
            </value>
            <value>
                <fullName>pending</fullName>
            </value>
            <value>
                <fullName>succeeded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Stripe_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer_Id__c</fullName>
    <description>Stripe customer id</description>
    <label>Stripe Customer Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Stripe_Invoice_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Invoice_Id__c</fullName>
    <label>Stripe Invoice Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Stripe_Payment_Intent_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Payment_Intent_Id__c</fullName>
    <description>Stripe Payment intent id</description>
    <label>Stripe Payment Intent Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Stripe_Payment_Method_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Payment_Method_Id__c</fullName>
    <label>Stripe Payment Method Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Decline_Code__mdt/Stripe_Decline_Code__mdt.object-meta.xml
<CustomObject>
    <label>Stripe Decline Code</label>
    <pluralLabel>Stripe Decline Codes</pluralLabel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Stripe_Decline_Code__mdt/fields/PAYMENT_RESULT__c.field-meta.xml
<CustomField>
    <fullName>PAYMENT_RESULT__c</fullName>
    <label>PAYMENT RESULT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fail Soft</fullName>
                <default>true</default>
                <label>Fail Soft</label>
            </value>
            <value>
                <fullName>Fail Hard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Setting__c/Stripe_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To handle settings for stripe integration</description>
    <label>Stripe Setting</label>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Stripe_Setting__c/fields/Activation__c.field-meta.xml
<CustomField>
    <fullName>Activation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activation</label>
    <type>Checkbox</type>
</CustomField>

care-australia-uat/force-app/main/default/classes/StripeChargeBatch.cls
public class StripeChargeBatch implements Database.Batchable<sObject> {
    String query;
    List<Charge__c> processedCharges = new List<Charge__c>();
    
    public StripeChargeBatch() {
        query = 'SELECT Id, Name, Is_Processed__c, Stripe_Charge_Id__c, Stripe_Payment_Intent_Id__c, Stripe_Charge_Status__c, ';
        query += 'Stripe_Customer_Id__c, Stripe_Invoice_Id__c, Stripe_Charge_Amount__c, Method_Type__c, Payment_Created_Date__c, ';
        query += 'Card_Last_Digits__c, Card_Type__c, Card_Token__c, Card_Expiration_Month__c, Card_Expiration_Year__c, ';
        query += 'Stripe_Payment_Method_Id__c, Failure_Code__c, Outcome_Reason__c, Campaign_Id__c, Is_Recurring__c, Donation_Source__c, ';
        query += 'Account_Token__c, Account_BSB__c, Account_Last_Digits__c, Opportunity_Id__c, Recurring_Donation_Id__c, ';
        query += 'RD_Installment_Every__c, RD_Installment_Period__c, RD_Installment_Effective_Date__c, RD_Installment_Day_Of_Month__c ';
        query += 'FROM Charge__c WHERE Is_Processed__c = false';
    } 
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Charge__c> charges) {
        try {
            System.debug('charges -> ' + charges);
            if(Stripe_Setting__c.getInstance('Default').Activation__c) { 
                Map<String, String> declineCodeMap = new Map<String, String>();
                for (Stripe_Decline_Code__mdt dc: [Select Id, DeveloperName, PAYMENT_RESULT__c From Stripe_Decline_Code__mdt]) {
                    declineCodeMap.put(dc.DeveloperName, dc.PAYMENT_RESULT__c);
                }
                
                Map<String, Charge__c> onePayChargesMap = new Map<String, Charge__c>();
                Map<String, Charge__c> invoiceChargeMap = new Map<String, Charge__c>();
                Set<String> customerIds = new Set<String>();
                
                for (Charge__c charge : charges) { 
                    if (charge.Stripe_Invoice_Id__c == null) {
                        onePayChargesMap.put(charge.Stripe_Charge_Id__c, charge);
                        List<String> splitCustomerId = charge.Stripe_Customer_Id__c.split('_');//Split the customer id for SOSL
                        customerIds.add('*' + splitCustomerId[1] + '*'); //to be considered in SOSL query as wildcard character
                    } else {
                        invoiceChargeMap.put(charge.Stripe_Invoice_Id__c, charge);
                    }
                }
                
                System.debug('onePayChargesMap -> ' + onePayChargesMap);
                System.debug('invoiceChargeMap -> ' + invoiceChargeMap);
                
                if (onePayChargesMap.size() > 0) {
                    ProcessChargeService.createOpportunityAndUpdatePaymentFromCharge(onePayChargesMap, customerIds, declineCodeMap);
                    processedCharges.addAll(onePayChargesMap.values());
                }
                
                if (invoiceChargeMap.size() > 0) {
                    ProcessChargeService.updateOpportunityAndPaymentFromCharge(invoiceChargeMap, declineCodeMap);
                    processedCharges.addAll(invoiceChargeMap.values());
                }
                
                if (processedCharges.size() > 0) {
                    System.debug('Processed charges to is processed true');
                    ProcessChargeService.updateProcessedCharges(processedCharges);
                }
            }
        } catch (Exception e) {
            ApexLogCreator.createApexLog('StripeChargeBatch', e.getMessage(), 'StripeChargeBatch', e.getStackTraceString());
        }
    }
    
    public void finish(Database.BatchableContext BC) {
        if (processedCharges.size() > 0) { 
            System.debug('Delete processed charges');
        	//delete processedCharges;
        }
    }
}