care-australia-uat/force-app/main/default/objects/Charge__c/Charge__c.object-meta.xml
<CustomObject>
    <description>Used to store charge coming from Stripe. The charge object will use in batch to update the respective Payment record.</description>
    <label>Charge</label>
    <nameField>
        <displayFormat>Ch-{00000000}</displayFormat>
        <label>Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Account_BSB__c.field-meta.xml
<CustomField>
    <fullName>Account_BSB__c</fullName>
    <label>Account BSB</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Account_Last_Digits__c.field-meta.xml
<CustomField>
    <fullName>Account_Last_Digits__c</fullName>
    <label>Account Last Digits</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Account_Token__c.field-meta.xml
<CustomField>
    <fullName>Account_Token__c</fullName>
    <label>Account Token</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Card_Expiration_Month__c.field-meta.xml
<CustomField>
    <fullName>Card_Expiration_Month__c</fullName>
    <label>Card Expiration Month</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Card_Expiration_Year__c.field-meta.xml
<CustomField>
    <fullName>Card_Expiration_Year__c</fullName>
    <label>Card Expiration Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Card_Last_Digits__c.field-meta.xml
<CustomField>
    <fullName>Card_Last_Digits__c</fullName>
    <label>Card Last Digits</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Card_Token__c.field-meta.xml
<CustomField>
    <fullName>Card_Token__c</fullName>
    <label>Card Token</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Is_Processed__c.field-meta.xml
<CustomField>
    <fullName>Is_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Will determine if the batch has been run successfully for the particular record</description>
    <label>Is Processed</label>
    <type>Checkbox</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Is_Recurring__c.field-meta.xml
<CustomField>
    <fullName>Is_Recurring__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Recurring</label>
    <type>Checkbox</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Payment_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Created_Date__c</fullName>
    <label>Payment Created Date</label>
    <type>Date</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Stripe_Charge_Amount__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Charge_Amount__c</fullName>
    <label>Stripe Charge Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Stripe_Charge_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Charge_Id__c</fullName>
    <description>External id of Charge, coming from Charge webhook response</description>
    <externalId>true</externalId>
    <label>Stripe Charge Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Stripe_Charge_Status__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Charge_Status__c</fullName>
    <description>Status of a Charge</description>
    <label>Stripe Charge Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>failed</fullName>
            </value>
            <value>
                <fullName>pending</fullName>
            </value>
            <value>
                <fullName>succeeded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Stripe_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer_Id__c</fullName>
    <description>Stripe customer id</description>
    <label>Stripe Customer Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Stripe_Invoice_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Invoice_Id__c</fullName>
    <label>Stripe Invoice Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Stripe_Payment_Intent_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Payment_Intent_Id__c</fullName>
    <description>Stripe Payment intent id</description>
    <label>Stripe Payment Intent Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Charge__c/fields/Stripe_Payment_Method_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Payment_Method_Id__c</fullName>
    <label>Stripe Payment Method Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{00000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Invoice__c/fields/Stripe_Charge_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Charge_Id__c</fullName>
    <label>Stripe Charge Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Invoice__c/fields/Stripe_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer_Id__c</fullName>
    <label>Stripe Customer Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Invoice__c/fields/Stripe_Invoice_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Invoice_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Stripe Invoice Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

care-australia-uat/force-app/main/default/objects/Invoice__c/fields/Stripe_Payment_Intent_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Payment_Intent_Id__c</fullName>
    <label>Stripe Payment Intent Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Invoice__c/fields/Stripe_Subscription_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Subscription_Id__c</fullName>
    <label>Stripe Subscription Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Charge_Settings__c/Stripe_Charge_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Use for Charge Object</description>
    <label>Stripe Charge Settings</label>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Stripe_Charge_Settings__c/fields/Type_of_donation_source__c.field-meta.xml
<CustomField>
    <fullName>Type_of_donation_source__c</fullName>
    <description>Add type of donation source if want to include the payment</description>
    <label>Type of donation source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Setting__c/Stripe_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To handle settings for stripe integration</description>
    <label>Stripe Setting</label>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Stripe_Setting__c/fields/Activation__c.field-meta.xml
<CustomField>
    <fullName>Activation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activation</label>
    <type>Checkbox</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Setting__c/fields/Default_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Default_Campaign__c</fullName>
    <label>Default Campaign</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Setting__c/fields/Default_Contact__c.field-meta.xml
<CustomField>
    <fullName>Default_Contact__c</fullName>
    <label>Default Contact</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/classes/StripeChargeBatchTest.cls
@isTest
public class StripeChargeBatchTest {
	@testSetup
    static void createTestData() {
        Account acc = new Account(Name='Test acc');
        insert acc;
        
        list<Contact> conList = new list<Contact>();
        conList.add(new Contact(AccountId=acc.Id, FirstName='Test', LastName='Customer', Email='test@test.com', npe01__PreferredPhone__c='Mobile', Phone='+61466666666', Stripe_Customer_Id__c='cus_OezvOgmGSxROgw', Stripe_Customer_Ids__c='cus_OezvOgmGSxROgw'));
        insert conList;
        
        Campaign parentCampaign = new Campaign(Name='Recurring Donation', IsActive=true);
        insert parentCampaign;
        
        Campaign camp = new Campaign(Name='2022 CAREGifts', ParentId=parentCampaign.Id, IsActive=true);
        insert camp;
        
        List<Charge__c> charges = new List<Charge__c>();
        
        Charge__c card_ch = new Charge__c();
        card_ch.Stripe_Charge_Id__c = 'ch_3NrfvyGGWgtqSxG40U8tXiA7';
        card_ch.Stripe_Charge_Status__c = 'succeeded';
        card_ch.Stripe_Customer_Id__c = 'cus_OezvOgmGSxROgw';
        card_ch.Stripe_Charge_Amount__c = 100;
        card_ch.Method_Type__c = 'card';
        card_ch.Payment_Created_Date__c = System.today();
        card_ch.Card_Last_Digits__c = '4242';
        card_ch.Card_Type__c = 'visa';
        card_ch.Card_Token__c = 'token';
        card_ch.Card_Expiration_Month__c = '01';
        card_ch.Card_Expiration_Year__c = '2024';
        card_ch.Stripe_Payment_Method_Id__c = 'paymentmethod';
        card_ch.Campaign_Id__c = String.valueOf(camp.Id);
        card_ch.Is_Recurring__c = true;
        card_ch.Is_Processed__c = false;
        
        charges.add(card_ch);
        
        Charge__c direct_ch = new Charge__c();
        direct_ch.Stripe_Charge_Id__c = 'ch_3NrfvyGGWgtqSxG40U8tXiA8';
        direct_ch.Stripe_Charge_Status__c = 'succeeded';
        direct_ch.Stripe_Customer_Id__c = 'cus_OezvOgmGSxROgw';
        direct_ch.Stripe_Charge_Amount__c = 100;
        direct_ch.Method_Type__c = 'au_becs_debit';
        direct_ch.Payment_Created_Date__c = System.today();
        direct_ch.Account_Last_Digits__c = '4242';
        direct_ch.Account_Token__c = 'token';
        direct_ch.Account_BSB__c = '01';
        direct_ch.Card_Expiration_Year__c = '2024';
        direct_ch.Stripe_Payment_Method_Id__c = 'paymentmethod';
        direct_ch.Campaign_Id__c = String.valueOf(camp.Id);
        direct_ch.Is_Recurring__c = false;
        direct_ch.Is_Processed__c = false;
        
        charges.add(direct_ch);
        
        Charge__c invoice_ch = new Charge__c();
        invoice_ch.Stripe_Charge_Id__c = 'ch_3NrfvyGGWgtqSxG40U8tXiA9';
        invoice_ch.Stripe_Charge_Status__c = 'succeeded';
        invoice_ch.Stripe_Customer_Id__c = 'cus_OezvOgmGSxROgw';
        invoice_ch.Stripe_Charge_Amount__c = 100;
        invoice_ch.Method_Type__c = 'card';
        invoice_ch.Payment_Created_Date__c = System.today();
        invoice_ch.Card_Last_Digits__c = '4242';
        invoice_ch.Card_Type__c = 'visa';
        invoice_ch.Card_Token__c = 'token';
        invoice_ch.Card_Expiration_Month__c = '01';
        invoice_ch.Card_Expiration_Year__c = '2024';
        invoice_ch.Stripe_Payment_Method_Id__c = 'paymentmethod';
        invoice_ch.Campaign_Id__c = String.valueOf(camp.Id);
        invoice_ch.Is_Recurring__c = true;
        invoice_ch.Is_Processed__c = false;
        invoice_ch.Stripe_Invoice_Id__c = 'in_3NrfvyGGWgtqSxG40U8tXiA9';
        
        charges.add(invoice_ch);
        
        insert charges;
        
        Invoice__c invoice = new Invoice__c();
        invoice.Stripe_Charge_Id__c = invoice_ch.Stripe_Charge_Id__c;
        invoice.Stripe_Customer_Id__c = invoice_ch.Stripe_Customer_Id__c;
        invoice.Stripe_Invoice_Id__c = invoice_ch.Stripe_Invoice_Id__c;
        invoice.Stripe_Payment_Intent_Id__c = invoice_ch.Stripe_Payment_Intent_Id__c;
        invoice.Stripe_Subscription_Id__c = 'subsId';
        insert invoice;
        
        insert new npe03__Recurring_Donation__c(
            npe03__Contact__c=conList[0].Id, 
            npe03__Amount__c=500,
            npe03__Recurring_Donation_Campaign__c=camp.Id, 
            npsp__CardExpirationMonth__c='09', 
            npsp__CardExpirationYear__c='2024', 
            npsp__CardLast4__c='2424', 
            Card_Number_Masked__c='',
            Card_Token__c='', 
            Card_Type__c='Visa',
            npsp__StartDate__c=date.today().addDays(15), 
            npsp__RecurringType__c='Fixed', 
            npsp__InstallmentFrequency__c=1, 
            npe03__Installment_Period__c='Weekly', 
            npe03__Installments__c=12, 
            Payment_Gateway__c='Stripe', 
            npsp__PaymentMethod__c='Credit Card',
            npsp__Status__c='Active',
            Stripe_Subscription_Id__c = 'subsId'
        );
        
        Stripe_Setting__c recSetting = new Stripe_Setting__c();
        recSetting.Name= 'Default';
        recSetting.Default_Contact__c = conList[0].id;
        recSetting.Default_Campaign__c = camp.id;
        recSetting.Activation__c = True;
        insert recSetting;
        
        Stripe_Charge_Settings__c mc = new Stripe_Charge_Settings__c();
        mc.Name= 'Default';
        mc.Type_of_donation_source__c = 'credit card';
        insert mc;
    }
    
    @isTest
    static void runBatch_StripeCharge() {
        Contact con = [SELECT Id FROM Contact];
        Id[] fixedSearchResults= new Id[1];
        fixedSearchResults[0] = con.Id;
        Test.setFixedSearchResults(fixedSearchResults);
        
        Test.startTest();
        StripeChargeBatch batch = new StripeChargeBatch();
        Database.executeBatch(batch);
        Test.stopTest();
    }
}