care-australia-uat/force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Loan__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <description>Used for Editable</description>
    <label>Loan</label>
</RecordType>

care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/Stripe_Payment_Configs__mdt.object-meta.xml
<CustomObject>
    <description>This metadata have the values of all the publish key and the domain required for the stripe payments.</description>
    <label>Stripe Payment Config</label>
    <pluralLabel>Stripe Payment Configs</pluralLabel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/fields/Donation_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Donation_Campaign__c</fullName>
    <label>Donation Campaign</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/fields/Donation_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Donation_Product_Name__c</fullName>
    <label>Donation Product Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/fields/Lend_With_Care_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Lend_With_Care_Campaign__c</fullName>
    <label>Lend With Care Campaign</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/fields/Loan_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product_Name__c</fullName>
    <label>Loan Product Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/fields/RD_Campaign__c.field-meta.xml
<CustomField>
    <fullName>RD_Campaign__c</fullName>
    <label>RD Campaign</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/fields/Topup_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Topup_Product_Name__c</fullName>
    <label>Topup Product Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Unique ID</description>
    <label>Lender</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Supporter</value>
        </filterItems>
        <filterItems>
            <field>Contact.IsLender__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan the transaction relates to</description>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Held</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Topup</fullName>
            </value>
            <value>
                <fullName>Repayment</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
                <label>Withdrawal / Refund</label>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
            <value>
                <fullName>FX Gain</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Expired Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/classes/CheckoutUtilityTest.cls
@isTest
public class CheckoutUtilityTest {
    static String email = 'abc@gmail.com';
    static String name = 'abc';
    
    static Map<String, Object> card = new Map<String, Object>();
	static Map<String, Object> cardWrap = new Map<String, Object>{
        'card' => card
    };
    static Map<String, Object> chargeObject = new Map<String, Object>{
        'payment_method_details' => cardWrap,
        'id' => 'ch_3LJ9eSGGWgtqSxG40QnBwDhY',
        'payment_method' => 'src_1LJ9eRGGWgtqSxG46k30tvhs',
        'object' => 'charge'
    };
    static Map<String, Object> charges = new Map<String, Object>{
        'data' => new List<Object>{chargeObject}     
    }; 
    static Map<String, Object> paymentIntentResponse = new Map<String, Object>{
        'charges' => charges,
        'object' => 'payment_intent'
    };  
    
    @testSetup
    static void createTestData() {
        Stripe_Payment_Configs__mdt metadataRecords = [SELECT Donation_Campaign__c, Lend_With_Care_Campaign__c, Donation_Product_Name__c, Loan_Product_Name__c, Topup_Product_Name__c, RD_Campaign__c FROM Stripe_Payment_Configs__mdt WHERE DeveloperName = 'Checkout_config'];
        String lendWithCareCampaign = metadataRecords.Lend_With_Care_Campaign__c;
        String donationCampaign = metadataRecords.Donation_Campaign__c;
        String loanProductName = metadataRecords.Loan_Product_Name__c;
        String topUpProductName = metadataRecords.Topup_Product_Name__c;
        String donationProductName = metadataRecords.Donation_Product_Name__c;
        String rdCampaign = metadataRecords.RD_Campaign__c;
        
        List<Campaign> campaigns = new List<Campaign>();
        campaigns.add(new Campaign(Name=lendWithCareCampaign, Campaign_Code__c=lendWithCareCampaign, IsActive=true));
        campaigns.add(new Campaign(Name=donationCampaign, Campaign_Code__c=donationCampaign, IsActive=true));
        campaigns.add(new Campaign(Name=rdCampaign, Campaign_Code__c=rdCampaign, IsActive=true));
        insert campaigns;
        
        campaigns[2].ParentId = campaigns[0].Id;
        update campaigns[2];
        
    	List<Product2> products = new List<Product2>();
        products.add(new Product2(Name=loanProductName, IsActive=true, CurrencyIsoCode='AUD'));
        products.add(new Product2(Name=topUpProductName, IsActive=true, CurrencyIsoCode='AUD'));
        products.add(new Product2(Name=donationProductName, IsActive=true, CurrencyIsoCode='AUD'));
        insert products;
        
        List<PricebookEntry> bookEntries = new List<PricebookEntry>();
        for(Product2 prod: products) {
         	bookEntries.add(new PricebookEntry(UnitPrice=1, Product2Id=prod.Id, Pricebook2Id=Test.getStandardPricebookId(), IsActive=true));   
        }
        insert bookEntries;
        
        card.put('brand', 'visa');
        card.put('fingerprint', 'nyNNNzbeuO4fqNe0');
        card.put('exp_month', '04');
        card.put('exp_year', '2024');
        card.put('last4', '2345');
    }
    
    @isTest
    static void processTransactionsAndPayment_whenChargeObject_WithoutLenderBalance() {
        Contact con = createContactData();
        List<Id> transIds = createTransaction(con);
        
        Test.startTest();
        CheckoutUtility.lenderName = name;
        CheckoutUtility.processTransactionsAndPayment(transIds, con, 0, chargeObject, email);
        Test.stopTest();
        
        assertResult();
    }
    
    @isTest
    static void processTransactionsAndPayment_whenPaymentIntentObject_WithLenderBalance() {
        Contact con = createContactData();
        List<Id> transIds = createTransaction(con);
        
        Test.startTest();
        CheckoutUtility.processTransactionsAndPayment(transIds, con, 10, paymentIntentResponse, email);
        Test.stopTest();
        
        assertResult();
    }
    
    @isTest
    static void processTransactionsAndPayment_whenPayPalObject_WithLenderBalance() {
        Contact con = createContactData();
        List<Id> transIds = createTransaction(con);
        
        Map<String, Object> paypalObject = new Map<String, Object>{
            'object' => 'paypal',
            'id' => 'paypalOId'
        };
        
        Test.startTest();
        CheckoutUtility.processTransactionsAndPayment(transIds, con, 10, paypalObject, email);
        Test.stopTest();
        
        assertResult();
    }
    
    @isTest
    static void processRD_test() {
        card.put('brand', 'visa');
        card.put('fingerprint', 'nyNNNzbeuO4fqNe0');
        card.put('exp_month', '04');
        card.put('exp_year', '2024');
        card.put('last4', '2345');
        card.put('id', 'card_asoiio123p9op0wdks');
        
        Contact con = createContactData();
        
        Test.startTest();
        CheckoutUtility.processRD(con, 10, cardWrap);
        Test.stopTest();
    }
    
    private static void assertResult() {
        for(Transaction__c trans: [SELECT Status__c FROM Transaction__c]) {
            Assert.areEqual('Completed', trans.Status__c, 'Transaction must be completed');
        }
    }
    
    private static Contact createContactData() {
        Account acc = new Account();
        acc.Name = 'Test Contact';
        insert acc;
        
        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Contact';
        con.Phone = '+61987654321';
        con.CurrencyIsoCode = 'AUD';
        con.Email = 'abc@gmail.com';
        con.AccountId = acc.Id;
        con.Active__c = true;
        con.IsLender__c = true;
        con.RecordTypeId = LWCUtility.getCustomerRecordTypeId();
        
        insert con;
        return con;
    }
    
    private static List<Id> createTransaction(Contact con) {
        List<User> fspStaffUsers = LWCTestUtility.getFSPStaffUsers();
        List<Contact> borrowers = LWCTestUtility.getBorrowerRecords(fspStaffUsers);        
       	List<Loan__c> loanList = LWCTestUtility.getBorrowerLoans(borrowers);
        
        List<Transaction__c> trans = new List<Transaction__c>();
        trans.add(new Transaction__c(Loan__c=loanList[0].Id, Lender__c=con.Id, Type__c='Loan', Amount__c=25, Status__c='Held',Transaction_Date__c=Date.today()));
        trans.add(new Transaction__c(Loan__c=loanList[0].Id, Lender__c=con.Id, Type__c='Donation', Amount__c=25, Status__c='Held',Transaction_Date__c=Date.today()));
        trans.add(new Transaction__c(Loan__c=loanList[0].Id, Lender__c=con.Id, Type__c='Topup', Amount__c=25, Status__c='Held',Transaction_Date__c=Date.today()));
        
        insert trans;
        
        return new List<Id>{trans[0].Id, trans[1].Id, trans[2].Id};
    }
}