care-australia-uat/force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Include_in_Offset_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Include_in_Offset_Calculation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include in Offset Calculation</label>
    <type>Checkbox</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Fundraising</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Written off</fullName>
            </value>
            <value>
                <fullName>Repaid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <description>Used for Editable</description>
    <label>Loan</label>
</RecordType>

care-australia-uat/force-app/main/default/classes/CheckFundedLoanSetup_FTScheduler.cls
/**
* Name			:		CheckFundedLoanSetup_FTScheduler
* Date			:		01/08/2023
* Author		:		Amit Goyal
* Description	:		MAD-478: the Finance team has not set the funded loans yet, 
							the Finance team should receive a reminder (chatter)
*/
global class CheckFundedLoanSetup_FTScheduler Implements Schedulable{
    @TestVisible private static string lwcAdminGrpId;
	global void execute(SchedulableContext sc)
    {
        Integer month=System.Today().addMonths(-1).Month();
        Integer year=System.Today().addMonths(-1).Year();
        
        // Get the first day of the month
        Date firstDayOfMonth = Date.newInstance(year, month, 1);
        // Get the last day of the month
        Integer lastDayOfMonth = Date.daysInMonth(year, month);
        Date lastDayDate = Date.newInstance(year, month, lastDayOfMonth);
        list<Loan__c> loans = [Select Id, Name, Stage__c, Funded_Date__c, Include_in_Offset_Calculation__c 
                               From Loan__c 
                               Where Stage__c='Active' 
                               AND (Funded_Date__c >=: firstDayOfMonth AND Funded_Date__c <=: lastDayDate)];
        Boolean notificationRequired=false;
        if(loans != null && loans.size()>0){
            for(Loan__c l: loans){
                if(!l.Include_in_Offset_Calculation__c){
                    notificationRequired=true;
                }
            }
            
            if(notificationRequired){
                list<Report> reports = [Select Id, Name From Report Where Name='LoanFullyFunded_LastMonth_CAFinance' limit 1];
                String lwcAdminGroupId;
                list<CollaborationGroup> groups = [SELECT Id FROM CollaborationGroup WHERE Name = 'LWC Admin' LIMIT 1];
                if(groups != null && groups.size()>0){
                    lwcAdminGroupId=groups[0].Id;
                }else{
                    if(Test.isRunningTest()){
                        lwcAdminGroupId=lwcAdminGrpId;
                    }
                }
                FeedItem post = new FeedItem();
                post.ParentId = lwcAdminGroupId;
                post.Type = 'LinkPost';
                post.Body = 'Some of the funded loan in last month are not set to get processed, please take action in 24 hours.';
                post.Title = 'Funded Loans need to set for Last month';
                if(reports != null && reports.size()>0){
                    post.LinkUrl = '/lightning/r/Report/' + reports[0].Id + '/view';
                    insert post;
                }
            }
        }
    }
    
}