care-australia-uat/force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Principal_Disbursed__c.field-meta.xml
<CustomField>
    <fullName>Loan_Principal_Disbursed__c</fullName>
    <description>Loan amount the borrower received in local currency</description>
    <label>Loan Principal Disbursed (LC)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Term_Months__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term_Months__c</fullName>
    <description>&quot;number of month for borrower to repay
displayed as Loan length on website&quot;</description>
    <label>Number of Repayments</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Repayment Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <label>Amount Due</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <label>Care Loan ID</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Loan_Repayment_Number__c.field-meta.xml
<CustomField>
    <fullName>Loan_Repayment_Number__c</fullName>
    <label>Loan Repayment Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/classes/LWC_RepaymentScheduleTableFlowActionTest.cls
@isTest
public class LWC_RepaymentScheduleTableFlowActionTest {
    @TestSetup
    private static void testData(){
        list<CollaborationGroup> cgList = LWCTestUtility.createCollaborationGroups(true);
        list<User> fspStaffUsers = LWCTestUtility.getFSPStaffUsers();
        list<Contact> borrowers = LWCTestUtility.getBorrowerRecords(fspStaffUsers);        
        list<Loan__c> loanList = LWCTestUtility.getBorrowerLoans(borrowers);
    }
    
    public testmethod static void testdeleterecords(){
        Loan__c l = [Select Id, Name, Loan_Term_Months__c, CurrencyIsoCode, Loan_Principal_Disbursed__c, 
                     (Select Id, Name, Loan__c, Amount_Due__c, Due_Date__c, Loan_Repayment_Number__c 
                      From Repayment_Schedules__r) 
                     From Loan__c limit 1];
        
        list<Repayment_Schedule__c> rsList = new list<Repayment_Schedule__c>();
        Decimal amount = l.Loan_Principal_Disbursed__c/l.Loan_Term_Months__c;
        for(Integer j=1; j<=l.Loan_Term_Months__c; j++){
            Date dt = System.Today();
            if(j==1){
                dt=dt.addDays(-20);
            }else if(j==2){
                
            }else{
                dt=dt.addDays(30);
            }
            rsList.add(new Repayment_Schedule__c(Loan__c=l.Id, Loan_Repayment_Number__c=j, Amount_Due__c=amount, Due_Date__c=dt));
        }
        insert rsList;
        Test.startTest();
        LWC_RepaymentScheduleTableFlowAction.deleterecords(String.valueOf(l.Id));
        Test.stopTest();
    }
    
    public testmethod static void testCreaterecords(){
        Loan__c l = [Select Id, Name, Loan_Term_Months__c, CurrencyIsoCode, Loan_Principal_Disbursed__c, 
                     (Select Id, Name, Loan__c, Amount_Due__c, Due_Date__c, Loan_Repayment_Number__c 
                      From Repayment_Schedules__r) 
                     From Loan__c limit 1];
        list<Repayment_Schedule__c> rsList = new list<Repayment_Schedule__c>();
        Decimal amount = l.Loan_Principal_Disbursed__c/l.Loan_Term_Months__c;
        for(Integer j=1; j<=l.Loan_Term_Months__c; j++){
            Date dt = System.Today();
            if(j==1){
                dt=dt.addDays(-20);
            }else if(j==2){
                
            }else{
                dt=dt.addDays(30);
            }
            rsList.add(new Repayment_Schedule__c(Loan__c=l.Id, Loan_Repayment_Number__c=j, Amount_Due__c=amount, Due_Date__c=dt));
        }
        Test.startTest();
        LWC_RepaymentScheduleTableFlowAction.createrecords(String.valueOf(l.Id), rsList.size(), rsList);
        Test.stopTest();
    }
    
    public testmethod static void testGetRepayment(){
        list<Loan__c> loanRecords = [Select Id, Name From Loan__c limit 1];
        Test.startTest();
        LWC_RepaymentScheduleTableFlowAction.getrepayment(loanRecords[0].Id);
        Test.stopTest();
    }
    
    public testmethod static void testUpdaterecords(){
        Loan__c l = [Select Id, Name, Loan_Term_Months__c, CurrencyIsoCode, Loan_Principal_Disbursed__c, 
                     (Select Id, Name, Loan__c, Amount_Due__c, Due_Date__c, Loan_Repayment_Number__c 
                      From Repayment_Schedules__r) 
                     From Loan__c limit 1];
        
        list<Repayment_Schedule__c> rsList = new list<Repayment_Schedule__c>();
        Decimal amount = l.Loan_Principal_Disbursed__c/l.Loan_Term_Months__c;
        for(Integer j=1; j<=l.Loan_Term_Months__c; j++){
            Date dt = System.Today();
            if(j==1){
                dt=dt.addDays(-20);
            }else if(j==2){
                
            }else{
                dt=dt.addDays(30);
            }
            rsList.add(new Repayment_Schedule__c(Loan__c=l.Id, Loan_Repayment_Number__c=j, Amount_Due__c=amount, Due_Date__c=dt));
        }
        insert rsList;
        Test.startTest();
        LWC_RepaymentScheduleTableFlowAction.updaterecords(String.valueOf(l.Id), rsList.size(), rsList);
        Test.stopTest();
    }
}