care-australia-uat/force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Borrower Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Borrower</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/CA_Themes__c.field-meta.xml
<CustomField>
    <fullName>CA_Themes__c</fullName>
    <description>high level themes according to CARE program strategy / targeting</description>
    <label>CA Themes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Climate Adaptation</fullName>
            </value>
            <value>
                <fullName>Climate Mitigation</fullName>
            </value>
            <value>
                <fullName>Women Led Business</fullName>
            </value>
            <value>
                <fullName>Increasing Women&apos;s Employment</fullName>
            </value>
            <value>
                <fullName>Disaster preparedness or response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Consent_Provided__c.field-meta.xml
<CustomField>
    <fullName>Consent_Provided__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The borrower has provided consent for their photo and name to appear on the platform.</description>
    <inlineHelpText>The borrower has provided consent for their photo and name to appear on the platform.</inlineHelpText>
    <label>Consent Provided (required)</label>
    <type>Checkbox</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Female_Employees_Count__c.field-meta.xml
<CustomField>
    <fullName>Female_Employees_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Female Employees Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/FSP_Loan_ID__c.field-meta.xml
<CustomField>
    <fullName>FSP_Loan_ID__c</fullName>
    <description>Loan ID in FSP system</description>
    <label>FSP Loan ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/FSP_Name__c.field-meta.xml
<CustomField>
    <fullName>FSP_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FSP Account Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans (FSP name)</relationshipLabel>
    <relationshipName>Loans1</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Jobs_Created__c.field-meta.xml
<CustomField>
    <fullName>Jobs_Created__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of new jobs created because of this loan, if any (including borrower &amp; partner)</description>
    <label>Jobs Created</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Description__c.field-meta.xml
<CustomField>
    <fullName>Loan_Description__c</fullName>
    <label>Loan Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Disbursement_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_Disbursement_Date__c</fullName>
    <description>Date the FSP / MFI disbursed the loan to the borrower</description>
    <label>Loan Disbursement Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Principal_Disbursed__c.field-meta.xml
<CustomField>
    <fullName>Loan_Principal_Disbursed__c</fullName>
    <description>Loan amount the borrower received in local currency</description>
    <label>Loan Principal Disbursed (LC)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Proposal_Status__c.field-meta.xml
<CustomField>
    <fullName>Loan_Proposal_Status__c</fullName>
    <label>Loan Proposal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>System Rejected</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Content Approved</fullName>
            </value>
            <value>
                <fullName>Ready to Publish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Loan_Purpose__c</fullName>
    <label>Loan Purpose</label>
    <length>110</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Loan_Schedule__c</fullName>
    <description>Monthly: One repayment made per month
End of term: One repayment made at the end of the loan term
Irregular: Any other repayment schedule</description>
    <label>Loan Schedule</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>End of Term</fullName>
            </value>
            <value>
                <fullName>Irregular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Term_Months__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term_Months__c</fullName>
    <description>&quot;number of month for borrower to repay
displayed as Loan length on website&quot;</description>
    <label>Number of Repayments</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Title__c.field-meta.xml
<CustomField>
    <fullName>Loan_Title__c</fullName>
    <label>Loan Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <description>Industry / sector</description>
    <label>Loan Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Art/Handicrafts</fullName>
            </value>
            <value>
                <fullName>Cafe/Restaurant</fullName>
            </value>
            <value>
                <fullName>Education/training</fullName>
            </value>
            <value>
                <fullName>Farming</fullName>
            </value>
            <value>
                <fullName>Fishing</fullName>
            </value>
            <value>
                <fullName>Green/Recycling</fullName>
            </value>
            <value>
                <fullName>Hairdressers/Beauty</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Refugees</fullName>
            </value>
            <value>
                <fullName>Retail - clothing and footwear</fullName>
            </value>
            <value>
                <fullName>Retail - grocery</fullName>
            </value>
            <value>
                <fullName>Sewing/Tailoring</fullName>
            </value>
            <value>
                <fullName>Tradesperson</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Number_of_Employees__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Employees__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Number of existing jobs</description>
    <label>Number of Employees</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Fundraising</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Written off</fullName>
            </value>
            <value>
                <fullName>Repaid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Repayment Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <label>Care Loan ID</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Loan_Repayment_Number__c.field-meta.xml
<CustomField>
    <fullName>Loan_Repayment_Number__c</fullName>
    <label>Loan Repayment Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/classes/LWC_ManageLoanApprovalQueueableTest.cls
@isTest
public class LWC_ManageLoanApprovalQueueableTest {
    @TestSetup
    private static void testData(){
        list<CollaborationGroup> cgList = LWCTestUtility.createCollaborationGroups(true);
        list<User> fspStaffUsers = LWCTestUtility.getFSPStaffUsers();
        list<Contact> borrowers = LWCTestUtility.getBorrowerRecords(fspStaffUsers);        
        Loan__c l = new Loan__c(Borrower__c=borrowers[0].Id, FSP_Name__c=borrowers[0].FSP_Name__c, FSP_Loan_ID__c='L-'+borrowers[0].FSP_Client_ID__c, 
                                Loan_Term_Months__c=3, Loan_Disbursement_Date__c=System.Today().addDays(-29), 
                                Loan_Principal_Disbursed__c=24000000, Loan_Schedule__c='Monthly', CurrencyISOCode='VND', 
                                Consent_Provided__c=true, Number_of_Employees__c=1, Jobs_Created__c=1, Female_Employees_Count__c=1,
                                Loan_Purpose__c='Farming', CA_Themes__c='Climate Mitigation', Loan_Type__c='Farming', 
                                Loan_Title__c='Help Farmer to grow', Loan_Description__c='So and So farmer need help in farming',
                                Loan_Proposal_Status__c='Draft', Stage__c='New');
        insert l;
        list<Repayment_Schedule__c> rsList = new list<Repayment_Schedule__c>();
        Decimal amount = l.Loan_Principal_Disbursed__c/l.Loan_Term_Months__c;
        for(Integer j=1; j<=l.Loan_Term_Months__c; j++){
            Date dt = System.Today();
            if(j==1){
                dt=dt.addDays(-20);
            }else if(j==2){
                
            }else{
                dt=dt.addDays(30);
            }
            Repayment_Schedule__c rs = LWCTestUtility.getRepaymentRecord(l.Id, amount, dt);
            rs.Loan_Repayment_Number__c=j;
            rsList.add(rs);
        }
        insert rsList;
    }
       public testmethod static void testApprovedNegative(){
        
                   
            Loan__c l = [Select Id, Name, CreatedById From Loan__c limit 1];
            
            // Submit the record for approval
            Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
            req.setComments('Submitting request for approval.');
            req.setSubmitterId(l.CreatedById);
            req.setSkipEntryCriteria(true);
            
             Test.startTest();
           try{
                Approval.ProcessResult result = Approval.process(req);
           }catch(Exception e){
               
           }
            Test.stopTest();
        
    }   
    public testmethod static void testApprovedPositive(){
        
                   
            Loan__c l = [Select Id, Name, CreatedById From Loan__c limit 1];
            
            // Submit the record for approval
            Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
            req.setComments('Submitting request for approval.');
            req.setSubmitterId(l.CreatedById);
            req.setObjectId(l.Id);
            req.setSkipEntryCriteria(true);
            Approval.ProcessResult result = Approval.process(req);
            
            // Verify that the record is now in the approval process
            System.assert(result.isSuccess());
            
            // Simulate the approval step
            List<Id> newWorkItemIds = result.getNewWorkitemIds();
            Test.setMock(HttpCalloutMock.class, new MockProcessWorkitemRequest());
            Approval.ProcessWorkitemRequest approveReq = new Approval.ProcessWorkitemRequest();
            approveReq.setComments('Test approval');
            approveReq.setAction('Approve');
            approveReq.setWorkitemId(newWorkItemIds.get(0));
            
             Test.startTest();
            Approval.ProcessResult approveResult = Approval.process(approveReq);
            Test.stopTest();
        
    }    
  
    public testmethod static void testApproved(){
        
        user usersR = [select id, email from user where Email='arnaud.charlier@care.org.au' AND isActive=true limit 1];
        if(usersR!=null)
        {
              System.runAs(usersR) {
            Test.startTest();
            Loan__c l = [Select Id, Name, CreatedById From Loan__c limit 1];
            
            // Submit the record for approval
            Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
            req.setComments('Submitting request for approval.');
            req.setSubmitterId(l.CreatedById);
            req.setObjectId(l.Id);
            req.setSkipEntryCriteria(true);
            Approval.ProcessResult result = Approval.process(req);
            
            // Verify that the record is now in the approval process
            System.assert(result.isSuccess());
            
            // Simulate the approval step
            List<Id> newWorkItemIds = result.getNewWorkitemIds();
            Test.setMock(HttpCalloutMock.class, new MockProcessWorkitemRequest());
            Approval.ProcessWorkitemRequest approveReq = new Approval.ProcessWorkitemRequest();
            approveReq.setComments('Test approval');
            approveReq.setAction('Approve');
            approveReq.setWorkitemId(newWorkItemIds.get(0));
            
            
            Approval.ProcessResult approveResult = Approval.process(approveReq);
            Test.stopTest();
        }
            
        }
      
    }    
    public testmethod static void testRejected(){
        Loan__c l = [Select Id, Name, CreatedById From Loan__c limit 1];
        
        // Submit the record for approval
        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
        req.setComments('Submitting request for approval.');
        req.setSubmitterId(l.CreatedById);
        req.setObjectId(l.Id);
        req.setSkipEntryCriteria(true);
        Approval.ProcessResult result = Approval.process(req);
        
        // Verify that the record is now in the approval process
        System.assert(result.isSuccess());
        
        List<Id> newWorkItemIds = result.getNewWorkitemIds();
        Test.setMock(HttpCalloutMock.class, new MockProcessWorkitemRequest());
        Approval.ProcessWorkitemRequest rejectReq = new Approval.ProcessWorkitemRequest();
        rejectReq.setComments('Test Photo rejection Missing Information');
        rejectReq.setAction('Reject');
        rejectReq.setWorkitemId(newWorkItemIds.get(0));
        Test.startTest();
        try{
            Approval.ProcessResult rejectResult = Approval.process(rejectReq);
        }catch(Exception e){}
        Test.stopTest();
    }
    
    public class MockProcessWorkitemRequest implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            // Create a mock response for the approval process request
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"success":true}');
            res.setStatusCode(200);
            return res;
        }
    }
}