care-australia-uat/force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Principal_Disbursed__c.field-meta.xml
<CustomField>
    <fullName>Loan_Principal_Disbursed__c</fullName>
    <description>Loan amount the borrower received in local currency</description>
    <label>Loan Principal Disbursed (LC)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <description>Used for Editable</description>
    <label>Loan</label>
</RecordType>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Repayment Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <label>Amount Due</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <label>Care Loan ID</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Loan_Repayment_Number__c.field-meta.xml
<CustomField>
    <fullName>Loan_Repayment_Number__c</fullName>
    <label>Loan Repayment Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/classes/LWC_RepaymentScheduleTableFlowAction.cls
public class LWC_RepaymentScheduleTableFlowAction{

    // Delete Repayment Schedule
    @AuraEnabled
    public static void deleterecords (String loanid ){
        System.debug(' loanid'+loanid);
        
        if( loanid != null && loanid.trim().length()>0 ){
            List<Repayment_Schedule__c> repaymentsTodelete = [SELECT Id, Name FROM Repayment_Schedule__c 
                                                                WHERE Loan__c =:loanid];

            if(repaymentsTodelete != null && repaymentsTodelete.size()>0){
                delete repaymentsTodelete;
            }                                                     
        }
    }

    // Create Repayment Schedule
    @AuraEnabled
    public static List<Repayment_Schedule__c> createrecords (String loanid, Integer loanterms, List<Repayment_Schedule__c> repayments){
        if(loanid != null && loanid.trim().length()>0){
                Loan__c loanRec = [ Select Id, Name, CurrencyIsoCode, Loan_Principal_Disbursed__c 
                                    From Loan__c 
                                    Where Id =: loanid];
            
            if(repayments != null && repayments.size()>0){
                if(loanterms == repayments.size()){
                    Decimal sumOfRepayment=0;
                    for(Repayment_Schedule__c re : repayments){
                        re.Loan__c = loanid;
                        re.CurrencyIsoCode = loanRec.CurrencyIsoCode;
                        re.Amount_Due__c = re.Amount_Due__c;
                        sumOfRepayment+=re.Amount_Due__c;
                        System.debug('@@@ repay Amount due after assignment '+ re.Amount_Due__c);
                        re.Due_Date__c = re.Due_Date__c;
                    }
                    if(loanRec.Loan_Principal_Disbursed__c!=sumOfRepayment){
                        System.debug('@@@ amount are not equal...');
                    }
                    insert repayments;
                    return repayments;
                }else{
                    // throw error
                    System.debug('@@@ loan term is not matching...');
                }
            }
        }
        return null;
    }

    // Get Repayment Schedule
     @AuraEnabled (cacheable= true)
    public static List<Repayment_Schedule__c> getrepayment(String recordID){
        List<Repayment_Schedule__c> repaymentlist= [ SELECT Id, Amount_Due__c, Due_Date__c,Loan__c,Loan_Repayment_Number__c 
                                                     FROM Repayment_Schedule__c
                                                     WHERE Loan__c =: recordID ORDER BY Due_Date__c ASC];
        return repaymentlist;
    }
    
    // Upsert Repayment Schedule
    @AuraEnabled (cacheable= false)
    public static List<Repayment_Schedule__c> updaterecords (String loanid, Integer loanterms, List<Repayment_Schedule__c> repayments){
        List<Repayment_Schedule__c> updatedRepayments = new List<Repayment_Schedule__c>();
       
        System.debug('Upsertrecords loanid'+loanid);
        System.debug('Upsertrecords loanterms'+loanterms);
        System.debug('Upsertrecords repayments'+repayments);
        
        if(loanid != null && loanid.trim().length()>0){
            List<Repayment_Schedule__c> existingRepayments = [ SELECT Id, Amount_Due__c, Due_Date__c,Loan__c,Loan_Repayment_Number__c
                                                               FROM Repayment_Schedule__c
                                                               WHERE Loan__c =: loanid ];
            system.debug('@@@ Existing Repayments : '+ existingRepayments);
            
            Loan__c loanrecord = [ Select Id, Name, CurrencyIsoCode, Loan_Principal_Disbursed__c 
                                   From Loan__c 
                                   Where Id =: loanid];
            
            if(repayments != null && repayments.size()>0){
                for(Repayment_Schedule__c repayment  : repayments){
                    Repayment_Schedule__c res = new Repayment_Schedule__c( Id=repayment.Id,
                                                                           Loan_Repayment_Number__c=repayment.Loan_Repayment_Number__c,
                                                                           Loan__c = loanid,
                                                                           CurrencyIsoCode = loanrecord.CurrencyIsoCode,
                                                                           Amount_Due__c=repayment.Amount_Due__c,
                                                                           Due_Date__c=repayment.Due_Date__c);
                            updatedRepayments.add(res);    
                }
                
                if(updatedRepayments != null && updatedRepayments.size()>0 ){
                    upsert updatedRepayments;
                }
                
            }
            return updatedRepayments;
        }
        return null;
    }
}