care-australia-uat/force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Expected_Funded_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Funded_Date__c</fullName>
    <label>Expected Funded Date</label>
    <type>Date</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Expired_Date__c.field-meta.xml
<CustomField>
    <fullName>Expired_Date__c</fullName>
    <label>Expired Date</label>
    <type>Date</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Fundraising</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Written off</fullName>
            </value>
            <value>
                <fullName>Repaid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <description>Used for Editable</description>
    <label>Loan</label>
</RecordType>

care-australia-uat/force-app/main/default/objects/LWC_Error_Log__c/LWC_Error_Log__c.object-meta.xml
<CustomObject>
    <label>LWC Error Log</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>LWC Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LWC Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Unique ID</description>
    <label>Lender</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Supporter</value>
        </filterItems>
        <filterItems>
            <field>Contact.IsLender__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan the transaction relates to</description>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Held</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Topup</fullName>
            </value>
            <value>
                <fullName>Repayment</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
                <label>Withdrawal / Refund</label>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
            <value>
                <fullName>FX Gain</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Expired Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/classes/LWC_LoanExpirationCheckScheduler.cls
/**
* Name			:		LWC_LoanExpirationCheckScheduler
* Date			:		15/07/2023
* Author		:		Amit Goyal
* Description	:		
*/
global class LWC_LoanExpirationCheckScheduler Implements Database.Batchable<sObject>, Schedulable{
	global void execute(SchedulableContext sc)
    {
        LWC_LoanExpirationCheckScheduler b = new LWC_LoanExpirationCheckScheduler();
        database.executebatch(b, 50);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Date dt = System.Today();
        String query = 'Select Id, Name, (Select Id, Name, Type__c, Transaction_Date__c, Status__c, Lender__c, Amount__c From Transactions__r Where Status__c=\'Completed\') From Loan__c Where Expected_Funded_Date__c <=: dt';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Loan__c> loans) {
        SavePoint sp = Database.setSavepoint();
        try {
            map<String, Loan__c> loansMap = new map<String, Loan__c>(loans);
            list<Transaction__c> repaymentTransactions = new list<Transaction__c>();
            for(Loan__c l: loans){
                system.debug('### Loan Name: '+l.Name);
                l.Stage__c='Expired';
                l.Expired_Date__c=System.Today();
                if(l.Transactions__r != null && l.Transactions__r.size()>0){
                    for(Transaction__c trans: l.Transactions__r){
                        if(trans.Type__c=='Loan'){
                            //Create a new reverse transaction for repayment.
                            repaymentTransactions.add(new Transaction__c(Loan__c=l.Id, Lender__c=trans.Lender__c, 
                                                                         Transaction_Date__c=System.Today(), Amount__c=trans.Amount__c, 
                                                                         Type__c='Expired Loan', Status__c='Held', CurrencyIsoCode='AUD'));
                        }
                        
                        if(trans.Type__c=='Voucher'){
                            // Generate a voucher and send to the lender
                        }
                    }
                }
            }
            
            update loans;
            
            if(repaymentTransactions != null && repaymentTransactions.size()>0){
                insert repaymentTransactions;
            }
        } catch(Exception e) {
            Database.rollback(sp);
            System.debug(e.getMessage());
            LWC_Error_Log__c err = new LWC_Error_Log__c(Class_Name__c='LWC_CalculateFSPBalance_8EMScheduler', MethodName__c='execute', 
                                                        Exception_Type__c='Error', Description__c=e.getMessage(), 
                                                        StackTrace__c=e.getStackTraceString());
            insert err;
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
}