care-australia-uat/force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Loan__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <description>Used for Editable</description>
    <label>Loan</label>
</RecordType>

care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/Stripe_Payment_Configs__mdt.object-meta.xml
<CustomObject>
    <description>This metadata have the values of all the publish key and the domain required for the stripe payments.</description>
    <label>Stripe Payment Config</label>
    <pluralLabel>Stripe Payment Configs</pluralLabel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/fields/Allow_Apple_Pay__c.field-meta.xml
<CustomField>
    <fullName>Allow_Apple_Pay__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Apple Pay</label>
    <type>Checkbox</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/fields/Allow_Credit_Card__c.field-meta.xml
<CustomField>
    <fullName>Allow_Credit_Card__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Credit Card</label>
    <type>Checkbox</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/fields/Allow_Google_Pay__c.field-meta.xml
<CustomField>
    <fullName>Allow_Google_Pay__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Google Pay</label>
    <type>Checkbox</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/fields/Allow_Paypal__c.field-meta.xml
<CustomField>
    <fullName>Allow_Paypal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Paypal</label>
    <type>Checkbox</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/fields/Donation_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Donation_Campaign__c</fullName>
    <label>Donation Campaign</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/fields/Donation_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Donation_Product_Name__c</fullName>
    <label>Donation Product Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/fields/Lend_With_Care_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Lend_With_Care_Campaign__c</fullName>
    <label>Lend With Care Campaign</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/fields/Loan_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Loan_Product_Name__c</fullName>
    <label>Loan Product Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/fields/RD_Campaign__c.field-meta.xml
<CustomField>
    <fullName>RD_Campaign__c</fullName>
    <label>RD Campaign</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/fields/Topup_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Topup_Product_Name__c</fullName>
    <label>Topup Product Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/fields/VF_page_domain__c.field-meta.xml
<CustomField>
    <fullName>VF_page_domain__c</fullName>
    <label>VF page domain</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Unique ID</description>
    <label>Lender</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Supporter</value>
        </filterItems>
        <filterItems>
            <field>Contact.IsLender__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan the transaction relates to</description>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Held</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Topup</fullName>
            </value>
            <value>
                <fullName>Repayment</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
                <label>Withdrawal / Refund</label>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
            <value>
                <fullName>FX Gain</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Expired Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/classes/StripePaymentControllerTest.cls
@isTest
public class StripePaymentControllerTest {
    static String email = 'abc@gmail.com';
    static String name = 'abc';
    
    @testSetup
    static void createTestData() {
        Stripe_Payment_Configs__mdt metadataRecords = [SELECT Donation_Campaign__c, Lend_With_Care_Campaign__c, Donation_Product_Name__c, Loan_Product_Name__c, Topup_Product_Name__c, RD_Campaign__c FROM Stripe_Payment_Configs__mdt WHERE DeveloperName = 'Checkout_config'];
        String lendWithCareCampaign = metadataRecords.Lend_With_Care_Campaign__c;
        String donationCampaign = metadataRecords.Donation_Campaign__c;
        String loanProductName = metadataRecords.Loan_Product_Name__c;
        String topUpProductName = metadataRecords.Topup_Product_Name__c;
        String donationProductName = metadataRecords.Donation_Product_Name__c;
        String rdCampaign = metadataRecords.RD_Campaign__c;
        
        List<Campaign> campaigns = new List<Campaign>();
        campaigns.add(new Campaign(Name=lendWithCareCampaign, Campaign_Code__c=lendWithCareCampaign, IsActive=true));
        campaigns.add(new Campaign(Name=donationCampaign, Campaign_Code__c=donationCampaign, IsActive=true));
        campaigns.add(new Campaign(Name=rdCampaign, Campaign_Code__c=rdCampaign, IsActive=true));
        insert campaigns;
        
        campaigns[2].ParentId = campaigns[0].Id;
        update campaigns[2];
        
    	List<Product2> products = new List<Product2>();
        products.add(new Product2(Name=loanProductName, IsActive=true, CurrencyIsoCode='AUD'));
        products.add(new Product2(Name=topUpProductName, IsActive=true, CurrencyIsoCode='AUD'));
        products.add(new Product2(Name=donationProductName, IsActive=true, CurrencyIsoCode='AUD'));
        insert products;
        
        List<PricebookEntry> bookEntries = new List<PricebookEntry>();
        for(Product2 prod: products) {
         	bookEntries.add(new PricebookEntry(UnitPrice=1, Product2Id=prod.Id, Pricebook2Id=Test.getStandardPricebookId(), IsActive=true));   
        }
        insert bookEntries;
    }
    
	@isTest
    static void getStripePaymentConfigs_returnConfigs() {
        Test.startTest();
        Stripe_Payment_Configs__mdt metadataRecords = StripePaymentController.getStripePaymentConfigs();
        Test.stopTest();
        
        Stripe_Payment_Configs__mdt testMetadataRecords = [SELECT Allow_Apple_Pay__c, Allow_Credit_Card__c, Allow_Google_Pay__c, Allow_Paypal__c, VF_page_domain__c FROM Stripe_Payment_Configs__mdt WHERE DeveloperName = 'Checkout_config'];
    	
        Assert.areEqual(testMetadataRecords.Allow_Apple_Pay__c, metadataRecords.Allow_Apple_Pay__c, 'Should match Allow_Apple_Pay__c of Checkout_config');
        Assert.areEqual(testMetadataRecords.Allow_Credit_Card__c, metadataRecords.Allow_Credit_Card__c, 'Should match Allow_Credit_Card__c of Checkout_config');
        Assert.areEqual(testMetadataRecords.Allow_Google_Pay__c, metadataRecords.Allow_Google_Pay__c, 'Should match Allow_Google_Pay__c of Checkout_config');
        Assert.areEqual(testMetadataRecords.Allow_Paypal__c, metadataRecords.Allow_Paypal__c, 'Should match Allow_Paypal__c of Checkout_config');
        Assert.areEqual(testMetadataRecords.VF_page_domain__c, metadataRecords.VF_page_domain__c, 'Should match VF_page_domain__c of Checkout_config');
    }
    
    @isTest
    static void processPaymentByCard_whenContactWithoutCustomerIdNoError_postCharge() {
        Contact con = createContactData();
        List<Id> transIds = createTransaction(con);
        
        Test.setMock(HttpCalloutMock.class, new StripePaymentController_Mocks.PostStripeChargeSuccess());
        
        Test.startTest();
        StripePaymentController.StripePaymentResponseWrapper response = StripePaymentController.processPaymentByCard(con.Id, 'tokenId', 'paymentTypeId', 1000, transIds, 0, email, name);
        Test.stopTest();
        
        Assert.areEqual(false, response.isError, 'isError should be false');
    }
    
    @isTest
    static void processPaymentByCard_whenContactWithoutCustomerIdErrorInCharge_returnErrorResponse() {
        Contact con = createContactData();
        List<Id> transIds = createTransaction(con);
        
        Test.setMock(HttpCalloutMock.class, new StripePaymentController_Mocks.PostStripeError());
        
        Test.startTest();
        StripePaymentController.StripePaymentResponseWrapper response = StripePaymentController.processPaymentByCard(con.Id, 'tokenId', 'paymentTypeId', 1000, transIds, 0, email, name);
        Test.stopTest();
        
        Assert.areEqual(true, response.isError, 'isError should be true');
    }
    
    @isTest
    static void processPaymentByCard_whenContactWithCustomerIdNoError_postCharge() {
        Contact con = createContactData();
        con.Stripe_Customer_Id__c = 'cus_5a651s56adfwe';
        update con;
        
        List<Id> transIds = createTransaction(con);
        
        Test.setMock(HttpCalloutMock.class, new StripePaymentController_Mocks.PostStripeChargeSuccess());
        
        Test.startTest();
        StripePaymentController.StripePaymentResponseWrapper response = StripePaymentController.processPaymentByCard(con.Id, 'tokenId', 'paymentTypeId', 1000, transIds, 0, email, name);
        Test.stopTest();
        
        Assert.areEqual(false, response.isError, 'isError should be false');
    }
    
    @isTest
    static void processPaymentByWallet_whenContactWithoutCustomerIdNoError_postPaymentIntent() {
        Contact con = createContactData();
        List<Id> transIds = createTransaction(con);
        
        Test.setMock(HttpCalloutMock.class, new StripePaymentController_Mocks.PostStripePaymentIntentSuccess());
        
        Test.startTest();
        StripePaymentController.StripePaymentResponseWrapper response = StripePaymentController.processPaymentByWallet(con.Id, 'tokenId', 1000, transIds, 0, email, name);
        Test.stopTest();
        
        Assert.areEqual(false, response.isError, 'isError should be false');
    }
    
    @isTest
    static void processPaymentByWallet_whenContactWithoutCustomerIdErrorInCharge_returnErrorResponse() {
        Contact con = createContactData();
        List<Id> transIds = createTransaction(con);
        
        Test.setMock(HttpCalloutMock.class, new StripePaymentController_Mocks.PostStripeError());
        
        Test.startTest();
        StripePaymentController.StripePaymentResponseWrapper response = StripePaymentController.processPaymentByWallet(con.Id, 'tokenId', 1000, transIds, 0, email, name);
        Test.stopTest();
        
        Assert.areEqual(true, response.isError, 'isError should be true');
    }
    
    @isTest
    static void processPaymentByCard_whenContactWithCustomerIdNoError_postPaymentIntent() {
        Contact con = createContactData();
        con.Stripe_Customer_Id__c = 'cus_5a651s56adfwe';
        update con;
        List<Id> transIds = createTransaction(con);
        
        Test.setMock(HttpCalloutMock.class, new StripePaymentController_Mocks.PostStripePaymentIntentSuccess());
        
        Test.startTest();
        StripePaymentController.StripePaymentResponseWrapper response = StripePaymentController.processPaymentByWallet(con.Id, 'tokenId', 1000, transIds, 0, email, name);
        Test.stopTest();
        
        Assert.areEqual(false, response.isError, 'isError should be false');
    }
    
    @isTest
    static void processRD_Test() {
        Map<String, Object> card = new Map<String, Object>();
        card.put('brand', 'visa');
        card.put('fingerprint', 'nyNNNzbeuO4fqNe0');
        card.put('exp_month', '04');
        card.put('exp_year', '2024');
        card.put('last4', '2345');
        card.put('id', 'card_asoiio123p9op0wdks');
		Map<String, Object> cardWrap = new Map<String, Object>{
        	'card' => card
    	};
            
        Contact con = createContactData();
        
        Test.setMock(HttpCalloutMock.class, new StripePaymentController_Mocks.PostStripeError());
        
        Test.startTest();
        StripePaymentController.StripePaymentResponseWrapper response = StripePaymentController.processRD(con.Id, 'tokenId', 'paymentTypeId', 1000, JSON.serialize(cardWrap));
        Test.stopTest();
        
        Assert.areEqual(true, response.isError, 'isError should be true');
    }
    
    @isTest
    static void processPayPal_test() {
        Contact con = createContactData();
        List<Id> transIds = createTransaction(con);
        
        Map<String, Object> paypalObject = new Map<String, Object>{
            'object' => 'paypal',
            'id' => 'paypalOId'
        };
        
        Test.startTest();
        StripePaymentController.StripePaymentResponseWrapper response = StripePaymentController.processPayPal(con.Id, JSON.serialize(paypalObject), transIds, 10, email, name);
        Test.stopTest();
        
        Assert.areEqual(false, response.isError, 'isError should be false');
    }
    
    private static Contact createContactData() {
        Contact con = new Contact();
        con.FirstName = 'Test';
        con.LastName = 'Contact';
        con.Phone = '+61987654321';
        con.CurrencyIsoCode = 'AUD';
        con.Email = 'abc@gmail.com';
        con.Active__c = true;
        con.IsLender__c = true;
        con.RecordTypeId = LWCUtility.getCustomerRecordTypeId();
        
        insert con;
        return con;
    }
    
    private static List<Id> createTransaction(Contact con) {
        List<User> fspStaffUsers = LWCTestUtility.getFSPStaffUsers();
        List<Contact> borrowers = LWCTestUtility.getBorrowerRecords(fspStaffUsers);        
       	List<Loan__c> loanList = LWCTestUtility.getBorrowerLoans(borrowers);
        
        Transaction__c trans = new Transaction__c(Loan__c=loanList[0].Id, Lender__c=con.Id, Type__c='Loan', Amount__c=25, Status__c='Completed',Transaction_Date__c=Date.today());
        
        insert trans;
        return new List<Id>{trans.Id};
    }
}