care-australia-uat/force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Borrower Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Borrower</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/CA_Themes__c.field-meta.xml
<CustomField>
    <fullName>CA_Themes__c</fullName>
    <description>high level themes according to CARE program strategy / targeting</description>
    <label>CA Themes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Climate Adaptation</fullName>
            </value>
            <value>
                <fullName>Climate Mitigation</fullName>
            </value>
            <value>
                <fullName>Women Led Business</fullName>
            </value>
            <value>
                <fullName>Increasing Women&apos;s Employment</fullName>
            </value>
            <value>
                <fullName>Disaster preparedness or response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Consent_Provided__c.field-meta.xml
<CustomField>
    <fullName>Consent_Provided__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The borrower has provided consent for their photo and name to appear on the platform.</description>
    <inlineHelpText>The borrower has provided consent for their photo and name to appear on the platform.</inlineHelpText>
    <label>Consent Provided (required)</label>
    <type>Checkbox</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Female_Employees_Count__c.field-meta.xml
<CustomField>
    <fullName>Female_Employees_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Female Employees Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/FSP_Loan_ID__c.field-meta.xml
<CustomField>
    <fullName>FSP_Loan_ID__c</fullName>
    <description>Loan ID in FSP system</description>
    <label>FSP Loan ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/FSP_Name__c.field-meta.xml
<CustomField>
    <fullName>FSP_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FSP Account Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans (FSP name)</relationshipLabel>
    <relationshipName>Loans1</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Jobs_Created__c.field-meta.xml
<CustomField>
    <fullName>Jobs_Created__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of new jobs created because of this loan, if any (including borrower &amp; partner)</description>
    <label>Jobs Created</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Disbursement_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_Disbursement_Date__c</fullName>
    <description>Date the FSP / MFI disbursed the loan to the borrower</description>
    <label>Loan Disbursement Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Principal_Disbursed__c.field-meta.xml
<CustomField>
    <fullName>Loan_Principal_Disbursed__c</fullName>
    <description>Loan amount the borrower received in local currency</description>
    <label>Loan Principal Disbursed (LC)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Principal_Disbursed_FSP_Txt__c.field-meta.xml
<CustomField>
    <fullName>Loan_Principal_Disbursed_FSP_Txt__c</fullName>
    <label>Loan Principal Disbursed (Portal)</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Loan_Purpose__c</fullName>
    <label>Loan Purpose</label>
    <length>110</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Loan_Schedule__c</fullName>
    <description>Monthly: One repayment made per month
End of term: One repayment made at the end of the loan term
Irregular: Any other repayment schedule</description>
    <label>Loan Schedule</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>End of Term</fullName>
            </value>
            <value>
                <fullName>Irregular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Term_Months__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term_Months__c</fullName>
    <description>&quot;number of month for borrower to repay
displayed as Loan length on website&quot;</description>
    <label>Number of Repayments</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Number_of_Employees__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Employees__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Number of existing jobs</description>
    <label>Number of Employees</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Published_Amount_AUD__c.field-meta.xml
<CustomField>
    <fullName>Published_Amount_AUD__c</fullName>
    <description>Principal + buffer</description>
    <label>Loan Principal Published</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Fundraising</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Written off</fullName>
            </value>
            <value>
                <fullName>Repaid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <description>Used for Editable</description>
    <label>Loan</label>
</RecordType>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Repayment Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <label>Care Loan ID</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Loan_Repayment_Number__c.field-meta.xml
<CustomField>
    <fullName>Loan_Repayment_Number__c</fullName>
    <label>Loan Repayment Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Underpaid</fullName>
            </value>
            <value>
                <fullName>Overpaid</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <label>Repaid</label>
            </value>
            <value>
                <fullName>Written off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Unique ID</description>
    <label>Lender</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Supporter</value>
        </filterItems>
        <filterItems>
            <field>Contact.IsLender__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan the transaction relates to</description>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Held</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Topup</fullName>
            </value>
            <value>
                <fullName>Repayment</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
                <label>Withdrawal / Refund</label>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
            <value>
                <fullName>FX Gain</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Expired Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/classes/LoanTriggerTest.cls
@isTest
public class LoanTriggerTest {
    @TestSetup
    private static void testData(){
        list<CollaborationGroup> cgList = LWCTestUtility.createCollaborationGroups(true);
        list<User> fspStaffUsers = LWCTestUtility.getFSPStaffUsers();
        list<Contact> borrowers = LWCTestUtility.getBorrowerRecords(fspStaffUsers);        
        list<Loan__c> loanList = LWCTestUtility.getBorrowerLoans(borrowers);
        list<Account> fspAccounts = LWCTestUtility.getFSPAccounts();
        list<Repayment_Schedule__c> rsList = new list<Repayment_Schedule__c>();
        for(Loan__c l: loanList){
            Decimal amount = l.Loan_Principal_Disbursed__c/l.Loan_Term_Months__c;
            for(Integer j=1; j<=l.Loan_Term_Months__c; j++){
                Date dt = System.Today();
                if(j==1){
                    dt=dt.addDays(-20);
                }else if(j==2){
                    
                }else{
                    dt=dt.addDays(30);
                }
                Repayment_Schedule__c rs = LWCTestUtility.getRepaymentRecord(l.Id, amount, dt);
                rs.Loan_Repayment_Number__c=j;
                rsList.add(rs);
            }
        }
        insert rsList;
        
        list<Contact> lenderContacts = LWCTestUtility.getLenderContacts();
        if(lenderContacts != null && lenderContacts.size()>0){
            list<String> lenderIds = new list<String>();
            list<Transaction__c> transactionList = new list<Transaction__c>();
            for(Loan__c l: loanList){
                system.debug('### Published_Amount_AUD__c: '+l.Published_Amount_AUD__c);
                if(lenderContacts[0].Id != null){
                    transactionList.add(new Transaction__c(Loan__c=l.Id, Lender__c=lenderContacts[0].Id, Type__c='Loan', Amount__c=25, Status__c='Completed'));
                    l.Stage__c='Active';
                }
            }
            try{
                insert transactionList;
            }
            catch(Exception e){
                system.debug('error Loantriggertest class 44 line '+ e);
            }
            
            update loanList;
        }
    }
    
    public testmethod static void testInsert(){
        Contact borrower = [Select Id, Name, FSP_Name__c, FSP_Client_ID__c From Contact Where Recordtype.Name='Borrower' limit 1];
        Loan__c l = new Loan__c(Borrower__c=borrower.Id, FSP_Name__c=borrower.FSP_Name__c, FSP_Loan_ID__c='L-'+borrower.FSP_Client_ID__c+'7378', 
                                Loan_Term_Months__c=3, Loan_Disbursement_Date__c=System.Today().addDays(-29), 
                                Loan_Principal_Disbursed_FSP_Txt__c='24000000', Loan_Schedule__c='Monthly', CurrencyISOCode='VND', 
                                Consent_Provided__c=true, Number_of_Employees__c=1, Jobs_Created__c=1, Female_Employees_Count__c=1,
                                Loan_Purpose__c='Farming', CA_Themes__c='Climate Mitigation', Loan_Type__c='Farming', 
                                Loan_Title__c='Help Farmer to grow', Loan_Description__c='So and So farmer need help in farming',
                                Loan_Proposal_Status__c='Draft', Stage__c='New', Loan_Principal_Disbursed__c=24000000);
        list<Loan__c> loans = new list<Loan__c>();
        for (Integer i = 1; i <= 50; i++) {
            loans.add(new Loan__c(
                Borrower__c =borrower.Id,
                FSP_Name__c = borrower.FSP_Name__c,
                FSP_Loan_ID__c = 'L-' + borrower.FSP_Client_ID__c + i,
                Loan_Term_Months__c = 3,
                Loan_Disbursement_Date__c = System.Today().addDays(-10),
                Loan_Principal_Disbursed_FSP_Txt__c = '24000000',
                Loan_Schedule__c = 'Monthly',
                CurrencyISOCode = 'VND',
                Consent_Provided__c = true,
                Number_of_Employees__c = 1,
                Jobs_Created__c = 1,
                Female_Employees_Count__c = 1,
                Loan_Purpose__c = 'Farming',
                CA_Themes__c = 'Climate Mitigation',
                Loan_Type__c = 'Farming',
                Loan_Title__c = 'Help Farmer to grow',
                Loan_Description__c = 'So and So farmer need help in farming',
                Loan_Proposal_Status__c = 'Draft',
                Stage__c = 'New',
                Loan_Principal_Disbursed__c = 24000000
            ));
            
            
        }
        Test.startTest();
        insert l;
        
        list<Repayment_Schedule__c> rsList = new list<Repayment_Schedule__c>();
        Decimal amount = l.Loan_Principal_Disbursed__c/l.Loan_Term_Months__c;
        //system.debug('### Loan_Principal_Disbursed__c for Loan - amount: '+l.Loan_Principal_Disbursed__c+' - '+amount);
        for(Integer j=1; j<=l.Loan_Term_Months__c; j++){
            Date dt = System.Today();
            if(j==1){
                dt=dt.addDays(-20);
            }else if(j==2){
                
            }else{
                dt=dt.addDays(30);
            }
            rsList.add(new Repayment_Schedule__c(Loan__c=l.Id, Loan_Repayment_Number__c=j, Amount_Due__c=amount, Due_Date__c=dt));
        }
        
        insert rsList;    
        Test.stopTest();
    }
     
    public testmethod static void testUpdate(){
        list<Loan__c> loanList = [Select Id, Name, Loan_Principal_Disbursed__c, Loan_Principal_Disbursed_AUD__c, 
                                  Published_Amount_AUD__c, Loan_Term_Months__c, Total_Repayment_Scheduled_Amount__c From Loan__c];
        for(Loan__c l: loanList){
            l.Loan_Proposal_Status__c='Under Review';
        }
        LoanTriggerHandler.hasRanAfterUpdate=false;
        update loanList;
        
        for(Loan__c l: loanList){
            l.Loan_Proposal_Status__c='System Rejected';
        }
        LoanTriggerHandler.hasRanAfterUpdate=false;
        update loanList;
        
        for(Loan__c l: loanList){
            l.Loan_Proposal_Status__c='Under Review';
        }
        LoanTriggerHandler.hasRanAfterUpdate=false;
        update loanList;
        
        for(Loan__c l: loanList){
            l.Loan_Proposal_Status__c='Content Approved';
        }
        LoanTriggerHandler.hasRanAfterUpdate=false;
        update loanList;
        
        for(Loan__c l: loanList){
            l.Loan_Proposal_Status__c='Ready To Publish';
            l.Stage__c='Scheduled';
        }
        LoanTriggerHandler.hasRanAfterUpdate=false;
        update loanList;
        
        for(Loan__c l: loanList){
            l.Loan_Proposal_Status__c='Published';
            l.Stage__c='Fundraising';
        }
        LoanTriggerHandler.hasRanAfterUpdate=false;
        update loanList;
    }
    
    public testmethod static void testUpdate1(){
        list<Loan__c> loanList = [Select Id, Name, Loan_Principal_Disbursed__c, Loan_Principal_Disbursed_AUD__c, 
                                  Published_Amount_AUD__c, Loan_Term_Months__c, Total_Repayment_Scheduled_Amount__c From Loan__c];
        for(Loan__c l: loanList){
            l.Loan_Proposal_Status__c='Under Review';
        }
        LoanTriggerHandler.hasRanAfterUpdate=false;
        update loanList;
        
        for(Loan__c l: loanList){
            l.Loan_Proposal_Status__c='System Rejected';
        }
        LoanTriggerHandler.hasRanAfterUpdate=false;
        update loanList;
        
        for(Loan__c l: loanList){
            l.Loan_Proposal_Status__c='Under Review';
        }
        LoanTriggerHandler.hasRanAfterUpdate=false;
        update loanList;
        
        for(Loan__c l: loanList){
            l.Loan_Proposal_Status__c='Content Approved';
            l.Manager_Approval_Request__c=true;
        }
        LoanTriggerHandler.hasRanAfterUpdate=false;
        update loanList;
        
        for(Loan__c l: loanList){
            l.Loan_Proposal_Status__c='Ready To Publish';
            l.Stage__c='Scheduled';
        }
        LoanTriggerHandler.hasRanAfterUpdate=false;
        update loanList;
        
        for(Loan__c l: loanList){
            l.Loan_Proposal_Status__c='Published';
            l.Stage__c='Fundraising';
        }
        LoanTriggerHandler.hasRanAfterUpdate=false;
        update loanList;
    }
    
    public testmethod static void testUpdate2(){
        list<Loan__c> loanList = [Select Id, Name, Loan_Principal_Disbursed__c, Loan_Principal_Disbursed_AUD__c, 
                                  Published_Amount_AUD__c, Loan_Term_Months__c, Total_Repayment_Scheduled_Amount__c From Loan__c];
        for(Loan__c l: loanList){
            l.Loan_Principal_Disbursed_USD__c=6000;
            l.Loan_Term_Months__c=10;
            l.Loan_Principal_Disbursed__c=73889255.92;
            l.Loan_Disbursement_Date__c=System.Today().addDays(-45);
        }
        update loanList;
        
        for(Loan__c l: loanList){
            l.Loan_Proposal_Status__c='Under Review';
        }
        LoanTriggerHandler.hasRanAfterUpdate=false;
        update loanList;
        
        for(Loan__c l: loanList){
            l.Loan_Proposal_Status__c='System Rejected';
        }
        LoanTriggerHandler.hasRanAfterUpdate=false;
        update loanList;
        
        for(Loan__c l: loanList){
            l.Loan_Proposal_Status__c='Under Review';
        }
        LoanTriggerHandler.hasRanAfterUpdate=false;
        update loanList;
        
        for(Loan__c l: loanList){
            l.Loan_Proposal_Status__c='Content Approved';
        }
        LoanTriggerHandler.hasRanAfterUpdate=false;
        update loanList;
        
        for(Loan__c l: loanList){
            l.Loan_Proposal_Status__c='Ready To Publish';
            l.Stage__c='Scheduled';
        }
        LoanTriggerHandler.hasRanAfterUpdate=false;
        update loanList;
        
        for(Loan__c l: loanList){
            l.Loan_Proposal_Status__c='Published';
            l.Stage__c='Fundraising';
        }
        LoanTriggerHandler.hasRanAfterUpdate=false;
        update loanList;
    }
    
    public testmethod static void testDelete(){
        list<Loan__c> loanList = [Select Id, Name, Loan_Principal_Disbursed__c, Loan_Principal_Disbursed_AUD__c, 
                                  Published_Amount_AUD__c, Loan_Term_Months__c, Total_Repayment_Scheduled_Amount__c From Loan__c];
        
        Test.startTest();
            delete loanList[0];
        Test.stopTest();
    }
    
    public testmethod static void testRepaid(){
        Loan__c loan = [Select Id, Name, Loan_Principal_Disbursed__c, Loan_Principal_Disbursed_AUD__c, 
                                  Published_Amount_AUD__c, Loan_Term_Months__c, Total_Repayment_Scheduled_Amount__c From Loan__c 
                                  Where Stage__c='Active' limit 1];
        
        Test.startTest();
        loan.Actual_Loan_Principle_Disbursed_AUD__c=loan.Published_Amount_AUD__c-50;
        loan.Buffer_To_Repay__c=50;
        loan.Total_Repaid_Amount_AUD__c=loan.Published_Amount_AUD__c-50;
        update loan;
        Test.stopTest();
    }
}