care-australia-uat/force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Borrower Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Borrower</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Cumulative_Amount_Expected_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Cumulative_Amount_Expected_To_Date__c</fullName>
    <label>Cumulative Amount Expected To Date (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Cumulative_Amount_Received_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Cumulative_Amount_Received_To_Date__c</fullName>
    <description>Addition from all previous repayments received to date.</description>
    <label>Cumulative Amount Received To Date (LC)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/FSP_Name__c.field-meta.xml
<CustomField>
    <fullName>FSP_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FSP Account Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans (FSP name)</relationshipLabel>
    <relationshipName>Loans1</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Last_Months_Expected_Repayment__c.field-meta.xml
<CustomField>
    <fullName>Last_Months_Expected_Repayment__c</fullName>
    <label>Last Month&apos;s Expected Repayment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Last_Repayment__c.field-meta.xml
<CustomField>
    <fullName>Last_Repayment__c</fullName>
    <description>last repayment amount received by CA</description>
    <label>Last Repayment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Last_Repayment_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Repayment_Date__c</fullName>
    <label>Last Repayment Date</label>
    <type>Date</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Disbursement_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_Disbursement_Date__c</fullName>
    <description>Date the FSP / MFI disbursed the loan to the borrower</description>
    <label>Loan Disbursement Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Nonperforming_Repayment_Count__c.field-meta.xml
<CustomField>
    <fullName>Nonperforming_Repayment_Count__c</fullName>
    <label>Nonperforming Repayment Count</label>
    <summaryFilterItems>
        <field>Repayment_Schedule__c.Non_performing_loan_options__c</field>
        <operation>notEqual</operation>
        <value></value>
    </summaryFilterItems>
    <summaryForeignKey>Repayment_Schedule__c.Loan__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Fundraising</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Written off</fullName>
            </value>
            <value>
                <fullName>Repaid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Total_Expected_Inc_Last_Month__c.field-meta.xml
<CustomField>
    <fullName>Total_Expected_Inc_Last_Month__c</fullName>
    <label>Total Expected Inc Last Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <description>Used for Editable</description>
    <label>Loan</label>
</RecordType>

care-australia-uat/force-app/main/default/objects/LWC_Config_Setting__mdt/LWC_Config_Setting__mdt.object-meta.xml
<CustomObject>
    <label>LWC Config Setting</label>
    <pluralLabel>LWC Config Settings</pluralLabel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/LWC_Config_Setting__mdt/fields/Missed_Repayments_Nonperforming__c.field-meta.xml
<CustomField>
    <fullName>Missed_Repayments_Nonperforming__c</fullName>
    <label>Missed Repayments Nonperforming</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Repayment Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <label>Amount Due</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <label>Care Loan ID</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Non_performing_loan_options__c.field-meta.xml
<CustomField>
    <fullName>Non_performing_loan_options__c</fullName>
    <description>list of options for FSP to select if loan is underpaid, this then gets communicated to the lenders for that loan.</description>
    <label>Non-performing loan options</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Loss of income</fullName>
            </value>
            <value>
                <fullName>Personal or family issues</fullName>
            </value>
            <value>
                <fullName>Natural disaster</fullName>
            </value>
            <value>
                <fullName>Unable to reach borrower (MFI issue)</fullName>
            </value>
            <value>
                <fullName>Comment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Principal_Repaid__c.field-meta.xml
<CustomField>
    <fullName>Principal_Repaid__c</fullName>
    <description>Amount paid off during reporting month (principal)</description>
    <label>Principal Repaid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Underpaid</fullName>
            </value>
            <value>
                <fullName>Overpaid</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <label>Repaid</label>
            </value>
            <value>
                <fullName>Written off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/classes/RepaymentScheduleTriggerHandler.cls
/**
* Name			:		RepaymentScheduleTriggerHandler
* Date			:		18/07/2023
* Author		:		Amit Goyal
* Description	:		FSP Repayment Template related field update
						Writing Off process related functionality - MAD-208
*/
public class RepaymentScheduleTriggerHandler {
    public static Boolean hasAlreadyRanAfterInsert=false;
    public static Boolean hasAlreadyRanAfterUpdate=false;
    public static Boolean hasAlreadyRanAfterDelete=false;
    public static Boolean hasAlreadyRanAfterUndelete=false;
    
    public static void handleBeforeInsert(list<Repayment_Schedule__c> newRepaymentSchedules){
        validateRepayments(Trigger.New);
    }
    
    public static void handleBeforeUpdate(list<Repayment_Schedule__c> newRepaymentSchedules){
        validateRepayments(Trigger.New);
    }
    
    public static void validateRepayments(list<Repayment_Schedule__c> newRepaymentSchedules){
        set<String> loanIds = new set<String>();
        for(Repayment_Schedule__c rs: newRepaymentSchedules){
            if(rs.Amount_Due__c < 0){
                rs.addError('Amount Due could not be less than zero.');
            }
            loanIds.add(rs.Loan__c);
        }
        
        map<String, Loan__c> loansMap = new map<String, Loan__c>([Select Id, Name, CurrencyISOCode, Loan_Disbursement_Date__c, Stage__c From Loan__c Where Id IN: loanIds]);
        for(Repayment_Schedule__c rs: newRepaymentSchedules){
            if(rs.Due_Date__c<loansMap.get(rs.Loan__c).Loan_Disbursement_Date__c){
                rs.addError('Due Date could not be older than Loan Disbursement Date.');
            }
            
            //system.debug('### '+rs.Due_Date__c+' - '+rs.Status__c+' - '+loansMap.get(rs.Loan__c).Stage__c);
            if(rs.Due_Date__c != null && (rs.Status__c==null || rs.Status__c=='') && loansMap.get(rs.Loan__c).Stage__c=='New'){
                rs.Repayment_Date__c=rs.Due_Date__c;
            }
            
            if(rs.Due_Date__c != null  && rs.Due_Date__c < System.Today() && (rs.Status__c==null || rs.Status__c=='') && loansMap.get(rs.Loan__c).Stage__c=='Fundraising'){
                if(rs.Repayment_Date__c==System.Today().addDays(-1)){
                    rs.Repayment_Date__c=rs.Due_Date__c.addMonths(1);
                }
            }
            rs.CurrencyISOCode=loansMap.get(rs.Loan__c).CurrencyISOCode;
        }
    }
    
    public static void handleAfterInsert(map<Id, Repayment_Schedule__c> newRepaymentSchedule){
        if(!hasAlreadyRanAfterInsert){
            hasAlreadyRanAfterInsert=true;
        }
        
        set<String> loanIdsRollup = new set<String>();
        for(Repayment_Schedule__c rs: newRepaymentSchedule.values()){
            loanIdsRollup.add(rs.Loan__c);
        }
        
        if(loanIdsRollup != null && loanIdsRollup.size()>0){
            rollupRepayments(loanIdsRollup);
        }
    }
    
    public static void handleAfterUpdate(map<Id, Repayment_Schedule__c> newRepaymentSchedule, map<Id, Repayment_Schedule__c> oldRepaymentSchedule){
        if(!hasAlreadyRanAfterUpdate){
            hasAlreadyRanAfterUpdate=true;
        }
        
        if(newRepaymentSchedule != null && newRepaymentSchedule.size()>0){
            set<String> loanIds = new set<String>();
            set<String> loanIdsRollup = new set<String>();
            for(Repayment_Schedule__c rs: newRepaymentSchedule.values()){
                if(rs.Non_performing_loan_options__c != null && rs.Non_performing_loan_options__c != oldRepaymentSchedule.get(rs.Id).Non_performing_loan_options__c){
                    loanIds.add(rs.Loan__c);
                }
                
                loanIdsRollup.add(rs.Loan__c);
                if(rs.Loan__c != oldRepaymentSchedule.get(rs.Id).Loan__c){
                    loanIdsRollup.add(oldRepaymentSchedule.get(rs.Id).Loan__c);
                }
            }
            
            if(loanIds != null && loanIds.size()>0){
                createTaskForNonperformingLoans(loanIds);
            }
            
            if(loanIdsRollup != null && loanIdsRollup.size()>0){
                rollupRepayments(loanIdsRollup);
            }
        }
    }
    
    public static void handleAfterDelete(map<Id, Repayment_Schedule__c> oldRepaymentSchedule){
        if(!hasAlreadyRanAfterDelete){
            hasAlreadyRanAfterDelete=true;
        }
        
        set<String> loanIdsRollup = new set<String>();
        for(Repayment_Schedule__c rs: oldRepaymentSchedule.values()){
            loanIdsRollup.add(rs.Loan__c);
        }
        
        if(loanIdsRollup != null && loanIdsRollup.size()>0){
            rollupRepayments(loanIdsRollup);
        }
    }
    
    public static void handleAfterUndelete(list<Repayment_Schedule__c> newRepaymentSchedule){
        if(!hasAlreadyRanAfterUndelete){
            hasAlreadyRanAfterUndelete=true;
        }
        
        set<String> loanIdsRollup = new set<String>();
        for(Repayment_Schedule__c rs: newRepaymentSchedule){
            loanIdsRollup.add(rs.Loan__c);
        }
        
        if(loanIdsRollup != null && loanIdsRollup.size()>0){
            rollupRepayments(loanIdsRollup);
        }
    }
    
    public static void rollupRepayments(set<String> loanIds){
        map<String, Loan__c> loansMap = new map<String, Loan__c>();
        list<String> repaymentStatus = new list<String>{'Underpaid', 'Overpaid', 'Paid', 'Skipped'};
            list<Loan__c> loans = [Select Id, Name, Last_Months_Expected_Repayment__c, Borrower__c,
                                   (Select Id, Name, Amount_Due__c, Principal_Repaid__c, Repayment_Date__c 
                                    From Repayment_Schedules__r 
                                    Where Status__c IN: repaymentStatus
                                    Order By Repayment_Date__c DESC) 
                                   From Loan__c 
                                   Where Id IN: loanIds];
        if(loans != null && loans.size()>0){
            for(Loan__c l: loans){
                Decimal amountExpectedToDate=0;
                Decimal amountReceivedToDate=0;
                Decimal totalExpectedIncLastMonth=0;
                if(l.Repayment_Schedules__r != null && l.Repayment_Schedules__r.size()>0){
                    l.Last_Repayment__c=l.Repayment_Schedules__r[0].Principal_Repaid__c;
                    l.Last_Repayment_Date__c=l.Repayment_Schedules__r[0].Repayment_Date__c;
                    for(Repayment_Schedule__c rs: l.Repayment_Schedules__r){
                        amountExpectedToDate+=rs.Amount_Due__c;
                        if(rs.Principal_Repaid__c != null && rs.Principal_Repaid__c>0){
                            amountReceivedToDate+=rs.Principal_Repaid__c;
                        }
                    }
                }
                l.Cumulative_Amount_Received_To_Date__c=amountReceivedToDate;
                l.Cumulative_Amount_Expected_To_Date__c=amountExpectedToDate;
                
                /*if(l.Cumulative_Amount_Expected_To_Date__c != null){
                    totalExpectedIncLastMonth=l.Cumulative_Amount_Expected_To_Date__c;
                }
                
                if(l.Last_Months_Expected_Repayment__c != null){
                    totalExpectedIncLastMonth+=l.Last_Months_Expected_Repayment__c;
                }
                l.Total_Expected_Inc_Last_Month__c=totalExpectedIncLastMonth;*/
                loansMap.put(l.Id, l);
            }
        }
        
        if(loansMap != null && loansMap.size()>0){
            update loansMap.values();
        }
    }
    
    public static void createTaskForNonperformingLoans(set<String> loanIds){
        LWC_Config_Setting__mdt lwcGlobalSettings = LWC_Config_Setting__mdt.getInstance('LWC_Global');
        list<Task> nonPerformingTasks = new list<Task>();
        if(loanIds != null && loanIds.size()>0){
            map<String, Loan__c> loansMap = new map<String, Loan__c>([Select Id, Name, FSP_Name__c, FSP_Name__r.Name, 
                                                                      (Select Id, Name, Non_performing_loan_options__c
                                                                       From Repayment_Schedules__r
                                                                       Where Non_performing_loan_options__c != null) 
                                                                      From Loan__c 
                                                                      Where Id IN: loanIds]);
            for(Loan__c l: loansMap.values()){
                if(l.Repayment_Schedules__r != null && l.Repayment_Schedules__r.size()>0){
                    //system.debug('### Nonperforming_Repayment_Count__c: '+l.Repayment_Schedules__r.size());
                    if(l.Repayment_Schedules__r.size() >= lwcGlobalSettings.Missed_Repayments_Nonperforming__c){
                        // create a task for the LWC admin to contact the FSP about the nonperforming loan
                        // LWC Admin - which user
                        list<Group> groups = [Select Id, Name From Group Where Name='LWC Admin' AND Type='Queue' limit 1];
                        String descTxt = 'This loan has been non-performing for '+lwcGlobalSettings.Missed_Repayments_Nonperforming__c+' month or more. please consider to contact the related FSP';
                        if(l.FSP_Name__c != null){
                            descTxt+=': '+l.FSP_Name__r.Name;
                        }
                        nonPerformingTasks.add(new Task(WhatId=l.Id, Subject='Non-Performing '+l.Name, 
                                                        Status='Not Started', Type='Email', 
                                                        ActivityDate=System.Today().addDays(7),
                                                       Description=descTxt, OwnerId=groups[0].Id, WhoId=l.FSP_Name__c));
                    }
                }
                
            }
            
            if(nonPerformingTasks != null && nonPerformingTasks.size()>0){
                insert nonPerformingTasks;
            }
        }
    }
    public static void increasePerformance(){
        Integer a=0, b=1, c=2;
        
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
        a= b+c;
    }
}