care-australia-uat/force-app/main/default/objects/Lender_Balance__c/Lender_Balance__c.object-meta.xml
<CustomObject>
    <label>Lender Balance</label>
    <nameField>
        <displayFormat>LB-{00000}</displayFormat>
        <label>Lender Balance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lender Balance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Lender_Balance__c/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Supporter</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Lender Balance</relationshipLabel>
    <relationshipName>Lender_Balance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Repaid_Date__c.field-meta.xml
<CustomField>
    <fullName>Repaid_Date__c</fullName>
    <label>Repaid Date</label>
    <type>Date</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Fundraising</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Written off</fullName>
            </value>
            <value>
                <fullName>Repaid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <description>Used for Editable</description>
    <label>Loan</label>
</RecordType>

care-australia-uat/force-app/main/default/objects/LWC_Config_Setting__mdt/LWC_Config_Setting__mdt.object-meta.xml
<CustomObject>
    <label>LWC Config Setting</label>
    <pluralLabel>LWC Config Settings</pluralLabel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/LWC_Config_Setting__mdt/fields/Campaign_BalanceDonation__c.field-meta.xml
<CustomField>
    <fullName>Campaign_BalanceDonation__c</fullName>
    <label>Campaign_BalanceDonation</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/LWC_Config_Setting__mdt/fields/Inactive_Lender_Limit_Days__c.field-meta.xml
<CustomField>
    <fullName>Inactive_Lender_Limit_Days__c</fullName>
    <label>Inactive Lender Limit (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/LWC_Error_Log__c/LWC_Error_Log__c.object-meta.xml
<CustomObject>
    <label>LWC Error Log</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>LWC Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LWC Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Repayment Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <label>Care Loan ID</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Underpaid</fullName>
            </value>
            <value>
                <fullName>Overpaid</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <label>Repaid</label>
            </value>
            <value>
                <fullName>Written off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Unique ID</description>
    <label>Lender</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Supporter</value>
        </filterItems>
        <filterItems>
            <field>Contact.IsLender__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan the transaction relates to</description>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Held</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Topup</fullName>
            </value>
            <value>
                <fullName>Repayment</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
                <label>Withdrawal / Refund</label>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
            <value>
                <fullName>FX Gain</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Expired Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/classes/LWC_DonateLenderBalanceInactiveLender.cls
/**
* Name			:		LWC_DonateLenderBalanceInactiveLender
* Date			:		07/09/2023
* Author		:		Sayan Baral
* Description	:		Find Inacitve Lenders and create donations against their Lender Balances
*/
global class LWC_DonateLenderBalanceInactiveLender Implements Database.Batchable<sObject>, Schedulable{
    global void execute(SchedulableContext sc)
    {
        LWC_DonateLenderBalanceInactiveLender b = new LWC_DonateLenderBalanceInactiveLender();
        database.executebatch(b, 20);
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        LWC_Config_Setting__mdt lwcGlobalSettings = LWC_Config_Setting__mdt.getInstance('LWC_Global');
        String query='SELECT Id, FirstName,Lender_Balance__c,';
        query+='(SELECT Id, Loan__r.Stage__c,Loan__r.Repaid_Date__c FROM Transactions__r  WHERE Type__c=\'Loan\' AND Status__c=\'Completed\' AND Loan__r.Stage__c=\'Active\') ';
        query+='FROM Contact WHERE ';
        if(!(Test.isRunningTest()))
        {
            query+='Id IN (SELECT ContactId FROM User WHERE IsActive = TRUE AND LastLoginDate != Last_N_Days: '+Integer.valueOf(lwcGlobalSettings.Inactive_Lender_Limit_Days__c)+' AND Profile.Name=\'Lender\') AND ';
        }
        query+='RecordType.Name=\'Supporter\'';
        return Database.getQueryLocator(query);       
    }
    global void execute(Database.BatchableContext BC, List<Contact> contactWithTransactions)
    {
        SavePoint sp = Database.setSavepoint();
        try
        {
            LWC_Config_Setting__mdt lwcGlobalSettings = LWC_Config_Setting__mdt.getInstance('LWC_Global');
            map<String, Contact> contactsMap = new map<String, Contact>(LWCUtility.getAllActiveLenders());
            List<Transaction__c> listTransact=new List<Transaction__c>();
            List<String> loanIds=new List<String>();
            Map<Contact,Set<String>> cont_Loan=new Map<Contact,Set<String>>();
            for(Contact c: contactWithTransactions) 
            {	
                if((c.Transactions__r.size()>0)&&(c.Lender_Balance__c>0))
                {
                    
                    for(Transaction__c t: c.Transactions__r)
                    {
                        loanIds.add(t.Loan__c);
                        Set<String> result = cont_Loan.get(c);
                        if(result==null)
                        {
                            result = new Set<String>();
                        }
                        result.add(t.Loan__c);
                        cont_Loan.put(c, result);
                    }
                }
            }
            List<Loan__c> loanWithRS=new List<Loan__c>();
            if(loanIds.size()>0)
            {
                loanWithRS=[SELECT Id,(SELECT Id FROM Repayment_Schedules__r WHERE Repayment_Date__c=NULL AND Status__c=NULL) FROM Loan__c WHERE Id IN :loanIds];
                
            }
            Map<String,boolean> isLoanRepayments=new Map<String,boolean>();
            if(loanWithRS.size()>0)
            {
                for(Loan__c l:loanWithRS)
                {
                    if(l.Repayment_Schedules__r.size()==0)
                        isLoanRepayments.put(l.Id,true);
                    else
                        isLoanRepayments.put(l.Id,false);
                }
            }
            
            for(Contact c: cont_Loan.keySet())
            {
                boolean isDonation=true;
                System.debug(cont_Loan.get(c)+'From class donateinactive');
                if(cont_Loan.get(c).size()>0)
                {
                    for(String loanId: cont_Loan.get(c))
                    {
                        if(isLoanRepayments.get(loanId)==false)
                        {
                            isDonation=false;
                            break;
                        }     
                    }
                    if(isDonation==true)
                    {
                        Transaction__c newDonate=new Transaction__c();
                        newDonate.Type__c='Donation';
                        newDonate.Amount__c=c.Lender_Balance__c;
                        newDonate.Lender__c=c.Id;
                        newDonate.Status__c='Completed';
                        newDonate.Transaction_Date__c=System.now();//additional values status->completed transaction date->today
                        listTransact.add(newDonate);
                    }
                }
            }
            if(listTransact.size()>0)
            {
                System.debug('List inserted--->'+listTransact);
                insert listTransact;
                
                String stdPriceBookId='';
                if(Test.isRunningTest()) {
                    stdPriceBookId = Test.getStandardPricebookId();
                } else {
                    stdPriceBookId = [SELECT Id FROM Pricebook2 WHERE IsStandard = true LIMIT 1].Id;
                }
                
                map<String, Transaction__c> oppTransactionMap = new map<String, Transaction__c>();
                list<Opportunity> oppList = new list<Opportunity>();
                String oppDonationRTId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Donation').getRecordTypeId();
                Campaign donationCampaign = [SELECT Id FROM Campaign WHERE Campaign_Code__c =: lwcGlobalSettings.Campaign_BalanceDonation__c LIMIT 1];
                for(Transaction__c trans: listTransact){
                    system.debug('### trans: '+trans.Loan__c+' - '+trans.Type__c+' - '+contactsMap.get(trans.Lender__c).Name+' - '+trans.Amount__c);
                    if(trans.Type__c=='Donation'){
                        Contact lenderContact = contactsMap.get(trans.Lender__c);
                        String oppName=lenderContact.Name + ' $' + trans.Amount__c;
                        oppList.add(new Opportunity(RecordTypeId=oppDonationRTId, Name=oppName, AccountId=lenderContact.AccountId, 
                                                    ContactId=lenderContact.Id, CurrencyIsoCode='AUD', CloseDate=Date.today(), 
                                                    StageName='Closed Won', Donation_Source__c='Auto Transfer', Type = 'LWC', Amount=trans.Amount__c,
                                                    CampaignId=donationCampaign.Id, Pricebook2Id=stdPriceBookId));
                        oppTransactionMap.put(oppName, trans);
                    }
                }
                system.debug('### oppList size: '+oppList.size());
                if(oppList != null && oppList.size()>0){
                    insert oppList;
                    
                    Product2 donationProduct = [SELECT Id FROM Product2 WHERE Name = 'Donation' LIMIT 1];
                    List<OpportunityLineItem> opplineItems = new List<OpportunityLineItem>();
                    for(Opportunity opp: oppList){
                        Transaction__c resultTrans = oppTransactionMap.get(opp.Name);
                        resultTrans.Opportunity__c=opp.Id;
                        oppTransactionMap.put(opp.Id, resultTrans);
                        opplineItems.add(new OpportunityLineItem(OpportunityId=opp.Id, Product2Id=donationProduct.Id, Quantity=opp.Amount, UnitPrice=1));
                    }
                    insert opplineItems;
                    
                    list<npe01__OppPayment__c> payments = [Select Id, Name, npe01__Opportunity__c From npe01__OppPayment__c Where npe01__Opportunity__c IN: oppList];
                    if(payments != null && payments.size()>0){
                        for(npe01__OppPayment__c p: payments){
                            p.npe01__Payment_Method__c='Internal Transfer';
                            p.Merchant_Category__c='LWC Transaction';
                            p.npe01__Check_Reference_Number__c=oppTransactionMap.get(p.npe01__Opportunity__c).Name;
                        }
                        update payments;
                    }
                    
                    map<String, Transaction__c> transactionsMap = new map<String, Transaction__c>();
                    for(Transaction__c t: oppTransactionMap.values()){
                        transactionsMap.put(t.Id, t);
                    }
                    update transactionsMap.values();
                }
            }
        }
        catch(Exception ex)
        {
            system.debug('### ex: '+ex+' - '+ex.getStackTraceString());
            Database.rollback(sp);
            System.debug('error--> '+ex.getMessage());
            LWC_Error_Log__c err = new LWC_Error_Log__c(Class_Name__c='LWCLenderRepaymentScheduler', MethodName__c='execute', 
                                                        Exception_Type__c='Error', Description__c=ex.getMessage(), 
                                                        StackTrace__c=ex.getStackTraceString());
            insert err;
        }
    }
    global void finish(Database.BatchableContext BC) {
        // execute any post-processing operations
    }
    
}