care-australia-uat/force-app/main/default/objects/Lender_Balance__c/Lender_Balance__c.object-meta.xml
<CustomObject>
    <label>Lender Balance</label>
    <nameField>
        <displayFormat>LB-{00000}</displayFormat>
        <label>Lender Balance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lender Balance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Lender_Balance__c/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <label>Lender</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Supporter</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Lender Balance</relationshipLabel>
    <relationshipName>Lender_Balance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Borrower Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Borrower</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/CA_Themes__c.field-meta.xml
<CustomField>
    <fullName>CA_Themes__c</fullName>
    <description>high level themes according to CARE program strategy / targeting</description>
    <label>CA Themes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Climate Adaptation</fullName>
            </value>
            <value>
                <fullName>Climate Mitigation</fullName>
            </value>
            <value>
                <fullName>Women Led Business</fullName>
            </value>
            <value>
                <fullName>Increasing Women&apos;s Employment</fullName>
            </value>
            <value>
                <fullName>Disaster preparedness or response</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Consent_Provided__c.field-meta.xml
<CustomField>
    <fullName>Consent_Provided__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The borrower has provided consent for their photo and name to appear on the platform.</description>
    <inlineHelpText>The borrower has provided consent for their photo and name to appear on the platform.</inlineHelpText>
    <label>Consent Provided (required)</label>
    <type>Checkbox</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Female_Employees_Count__c.field-meta.xml
<CustomField>
    <fullName>Female_Employees_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Female Employees Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/FSP__c.field-meta.xml
<CustomField>
    <fullName>FSP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FSP</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/FSP_Loan_ID__c.field-meta.xml
<CustomField>
    <fullName>FSP_Loan_ID__c</fullName>
    <description>Loan ID in FSP system</description>
    <label>FSP Loan ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/FSP_Name__c.field-meta.xml
<CustomField>
    <fullName>FSP_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FSP Account Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans (FSP name)</relationshipLabel>
    <relationshipName>Loans1</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Jobs_Created__c.field-meta.xml
<CustomField>
    <fullName>Jobs_Created__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of new jobs created because of this loan, if any (including borrower &amp; partner)</description>
    <label>Jobs Created</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Disbursement_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_Disbursement_Date__c</fullName>
    <description>Date the FSP / MFI disbursed the loan to the borrower</description>
    <label>Loan Disbursement Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Principal_Disbursed__c.field-meta.xml
<CustomField>
    <fullName>Loan_Principal_Disbursed__c</fullName>
    <description>Loan amount the borrower received in local currency</description>
    <label>Loan Principal Disbursed (LC)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Loan_Purpose__c</fullName>
    <label>Loan Purpose</label>
    <length>110</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Loan_Schedule__c</fullName>
    <description>Monthly: One repayment made per month
End of term: One repayment made at the end of the loan term
Irregular: Any other repayment schedule</description>
    <label>Loan Schedule</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>End of Term</fullName>
            </value>
            <value>
                <fullName>Irregular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Term_Months__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term_Months__c</fullName>
    <description>&quot;number of month for borrower to repay
displayed as Loan length on website&quot;</description>
    <label>Number of Repayments</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Title__c.field-meta.xml
<CustomField>
    <fullName>Loan_Title__c</fullName>
    <label>Loan Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <description>Industry / sector</description>
    <label>Loan Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Art/Handicrafts</fullName>
            </value>
            <value>
                <fullName>Cafe/Restaurant</fullName>
            </value>
            <value>
                <fullName>Education/training</fullName>
            </value>
            <value>
                <fullName>Farming</fullName>
            </value>
            <value>
                <fullName>Fishing</fullName>
            </value>
            <value>
                <fullName>Green/Recycling</fullName>
            </value>
            <value>
                <fullName>Hairdressers/Beauty</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Refugees</fullName>
            </value>
            <value>
                <fullName>Retail - clothing and footwear</fullName>
            </value>
            <value>
                <fullName>Retail - grocery</fullName>
            </value>
            <value>
                <fullName>Sewing/Tailoring</fullName>
            </value>
            <value>
                <fullName>Tradesperson</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Number_of_Employees__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Employees__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Number of existing jobs</description>
    <label>Number of Employees</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <description>Used for Editable</description>
    <label>Loan</label>
</RecordType>

care-australia-uat/force-app/main/default/objects/LWC_Config_Setting__mdt/LWC_Config_Setting__mdt.object-meta.xml
<CustomObject>
    <label>LWC Config Setting</label>
    <pluralLabel>LWC Config Settings</pluralLabel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/LWC_Config_Setting__mdt/fields/Campaign_AutoRelendDonation__c.field-meta.xml
<CustomField>
    <fullName>Campaign_AutoRelendDonation__c</fullName>
    <label>Campaign_AutoRelendDonation</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/LWC_Config_Setting__mdt/fields/Campaign_BalanceDonation__c.field-meta.xml
<CustomField>
    <fullName>Campaign_BalanceDonation__c</fullName>
    <label>Campaign_BalanceDonation</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/LWC_Config_Setting__mdt/fields/Campaign_GeneralDonation__c.field-meta.xml
<CustomField>
    <fullName>Campaign_GeneralDonation__c</fullName>
    <label>Campaign_GeneralDonation</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Repayment Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <label>Care Loan ID</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Unique ID</description>
    <label>Lender</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Supporter</value>
        </filterItems>
        <filterItems>
            <field>Contact.IsLender__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan the transaction relates to</description>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Topup</fullName>
            </value>
            <value>
                <fullName>Repayment</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
                <label>Withdrawal / Refund</label>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
            <value>
                <fullName>FX Gain</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Expired Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/classes/LWC_CheckoutEmailTest.cls
@isTest
public class LWC_CheckoutEmailTest {
    @TestSetup
    private static void testData(){
        LWC_Config_Setting__mdt lwcGlobalSettings = LWC_Config_Setting__mdt.getInstance('LWC_Global');
        list<Campaign> parentCampaignList = new list<Campaign>();
        parentCampaignList.add(new Campaign(Name='Donation', IsActive=true, Campaign_Code__c=lwcGlobalSettings.Campaign_GeneralDonation__c));
        parentCampaignList.add(new Campaign(Name='LenderBalance', IsActive=true, Campaign_Code__c=lwcGlobalSettings.Campaign_BalanceDonation__c));
        parentCampaignList.add(new Campaign(Name='AutoRelend', IsActive=true, Campaign_Code__c=lwcGlobalSettings.Campaign_AutoRelendDonation__c));
        insert parentCampaignList;
        
        String customerRTId=LWCUtility.getCustomerRecordTypeId();
        Contact fxGain = new Contact(RecordTypeId=customerRTId, FirstName='LWC FX', LastName = 'Lender', IsLender__c=true);
        insert fxGain;
        list<CollaborationGroup> cgList = LWCTestUtility.createCollaborationGroups(true);
        list<User> fspStaffUsers = LWCTestUtility.getFSPStaffUsers();
        list<Contact> borrowers = LWCTestUtility.getBorrowerRecords(fspStaffUsers);
        Account fspAccount = LWCTestUtility.getFSPAccountRecord();
        Loan__c oldLoan = new Loan__c(Borrower__c=borrowers[0].Id, FSP__c=fspAccount.Id, FSP_Name__c=borrowers[0].FSP_Name__c, FSP_Loan_ID__c='L-'+borrowers[0].FSP_Client_ID__c+'X', 
                                      Loan_Term_Months__c=3, Loan_Disbursement_Date__c=System.Today().addDays(-89), 
                                      Loan_Principal_Disbursed__c=24000000, Loan_Schedule__c='Monthly', CurrencyISOCode='VND', 
                                      Consent_Provided__c=true, Number_of_Employees__c=1, Jobs_Created__c=1, Female_Employees_Count__c=1,
                                      Loan_Purpose__c='Farming', CA_Themes__c='Climate Mitigation', Loan_Type__c='Farming', 
                                      Loan_Title__c='Help Farmer to grow', Loan_Description__c='So and So farmer need help in farming',
                                      Loan_Proposal_Status__c='Published', Stage__c='Active', Funded_Date__C=System.Today().addMonths(-2));
        insert oldLoan;
        
        list<Repayment_Schedule__c> oldrsList = new list<Repayment_Schedule__c>();
        Decimal amount1 = oldLoan.Loan_Principal_Disbursed__c/oldLoan.Loan_Term_Months__c;
        for(Integer j=1; j<=oldLoan.Loan_Term_Months__c; j++){
            Date dt = System.Today();
            if(j==1){
                dt=dt.addDays(-58);
            }else if(j==2){
                dt=dt.addDays(-28);
            }else{
                dt=dt.addDays(2);
            }
            Repayment_Schedule__c rs = LWCTestUtility.getRepaymentRecord(oldLoan.Id, amount1, dt);
            system.debug('rs-> '+rs);
            rs.Loan_Repayment_Number__c=j;
            oldrsList.add(rs);
        }
        insert oldrsList;
        
        
        list<Loan__c> loanList = LWCTestUtility.getBorrowerLoans(borrowers);
        list<Account> fspAccounts = LWCTestUtility.getFSPAccounts();
        list<Repayment_Schedule__c> rsList = new list<Repayment_Schedule__c>();
        for(Loan__c l: loanList){
            Decimal amount = l.Loan_Principal_Disbursed__c/l.Loan_Term_Months__c;
            for(Integer j=1; j<=l.Loan_Term_Months__c; j++){
                Date dt = System.Today();
                if(j==1){
                    dt=dt.addDays(-20);
                }else if(j==2){
                    
                }else{
                    dt=dt.addDays(30);
                }
                Repayment_Schedule__c rs = LWCTestUtility.getRepaymentRecord(l.Id, amount, dt);
                system.debug('rs-> '+rs);
                rs.Loan_Repayment_Number__c=j;
                rsList.add(rs);
            }
        }
        insert rsList;
        
        for(Loan__c l: loanList){
            l.Loan_Proposal_Status__c='Published';
            l.Stage__c='Fundraising';
            l.Funded_Date__C=System.Today().addMonths(-2);
        }
        update loanList;
        
    }
    
    public static testmethod void testsendCheckoutEmail(){
        LWC_Config_Setting__mdt lwcGlobalSettings = LWC_Config_Setting__mdt.getInstance('LWC_Global');
        List<Loan__c> loanList = [select id from Loan__c Where Stage__c='Fundraising' limit 10];
        map<String, Contact> contactsMap = new  map<String, Contact>(LWCTestUtility.getLenderContacts());
        for(Contact con: contactsMap.values()){
            con.Email='test@test.com';
            contactsMap.put(con.Id, con);
        }
        update contactsMap.values();
        
        system.debug('lenderContacts '+contactsMap.size());
        map<String, Lender_Balance__c> lenderBalanceMap = LWCTestUtility.getLenderBalances(contactsMap.values());
        system.debug('lenderBalanceMap--> '+lenderBalanceMap);
        List<Transaction__c> tranList = new List<Transaction__c>();
        tranList.add(new Transaction__c(Amount__c = 25, Added_To_Cart__c=true, Lender_Email__c='test@test.com', Type__c = 'Loan', Loan__c = loanList[0].id, status__c = 'Held', Lender__c = contactsMap.values()[0].Id, Transaction_Date__c=System.Now()));
        tranList.add(new Transaction__c(Amount__c = 100, Added_To_Cart__c=true, Type__c = 'Topup', status__c = 'Held', Lender__c = contactsMap.values()[0].Id, Transaction_Date__c=System.Now()));
        insert tranList;
        
        String stdPriceBookId='';
        if(Test.isRunningTest()) {
            stdPriceBookId = Test.getStandardPricebookId();
        } else {
            stdPriceBookId = [SELECT Id FROM Pricebook2 WHERE IsStandard = true LIMIT 1].Id;
        }
        
        map<String, Transaction__c> oppTransactionMap = new map<String, Transaction__c>();
        list<Opportunity> oppList = new list<Opportunity>();
        String oppDonationRTId=Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Donation').getRecordTypeId();
        Campaign donationCampaign = [SELECT Id FROM Campaign WHERE Campaign_Code__c =: lwcGlobalSettings.Campaign_GeneralDonation__c LIMIT 1];
        for(Transaction__c trans: tranList){
            Contact lenderContact = contactsMap.get(trans.Lender__c);
            String oppName=lenderContact.Name + ' $' + trans.Amount__c;
            oppList.add(new Opportunity(RecordTypeId=oppDonationRTId, Name=oppName, AccountId=lenderContact.AccountId, 
                                        ContactId=lenderContact.Id, CurrencyIsoCode='AUD', CloseDate=Date.today(), 
                                        StageName='Closed Won', Donation_Source__c='Auto Transfer', Type = 'LWC', Amount=trans.Amount__c,
                                        CampaignId=donationCampaign.Id, Pricebook2Id=stdPriceBookId));
            
        }
        system.debug('### oppList size: '+oppList.size());
        if(oppList != null && oppList.size()>0){
            insert oppList;
        }
        
        Test.startTest();
        Integer i=0;
        for(Transaction__c trans: tranList){
            trans.Opportunity__c=oppList[0].Id;
            trans.Status__c='Completed';
            trans.Completed_Date__c=System.Now();
            i++;
        }
        update tranList;
        Test.stopTest();
    }
    
}