care-australia-uat/force-app/main/default/objects/Lender_Balance__c/Lender_Balance__c.object-meta.xml
<CustomObject>
    <label>Lender Balance</label>
    <nameField>
        <displayFormat>LB-{00000}</displayFormat>
        <label>Lender Balance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lender Balance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Principal_Disbursed__c.field-meta.xml
<CustomField>
    <fullName>Loan_Principal_Disbursed__c</fullName>
    <description>Loan amount the borrower received in local currency</description>
    <label>Loan Principal Disbursed (LC)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Term_Months__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term_Months__c</fullName>
    <description>&quot;number of month for borrower to repay
displayed as Loan length on website&quot;</description>
    <label>Number of Repayments</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <description>Used for Editable</description>
    <label>Loan</label>
</RecordType>

care-australia-uat/force-app/main/default/objects/LWC_Config_Setting__mdt/LWC_Config_Setting__mdt.object-meta.xml
<CustomObject>
    <label>LWC Config Setting</label>
    <pluralLabel>LWC Config Settings</pluralLabel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Repayment Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <label>Amount Due</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <label>Care Loan ID</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Loan_Repayment_Number__c.field-meta.xml
<CustomField>
    <fullName>Loan_Repayment_Number__c</fullName>
    <label>Loan Repayment Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Underpaid</fullName>
            </value>
            <value>
                <fullName>Overpaid</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <label>Repaid</label>
            </value>
            <value>
                <fullName>Written off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan the transaction relates to</description>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Held</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/classes/LWCUtilityTest.cls
@isTest
public class LWCUtilityTest {
    
    @testSetup
    static void setupTestData() {
        // Create a test user record
        User testUser = new User(
            FirstName = 'Test',
            LastName = 'User',
            Email = 'testuser@example.com',
            Alias = 'TUser',
            Username = 'managertest@queue.com',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User'].Id, // Replace with the correct profile name
            TimeZoneSidKey = 'GMT',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        );
        insert testUser;
    }
    
    



    public testmethod static void testGetLenderTransaction(){
        list<CollaborationGroup> cgList = LWCTestUtility.createCollaborationGroups(true);
        list<User> fspStaffUsers = LWCTestUtility.getFSPStaffUsers();
        list<Contact> borrowers = LWCTestUtility.getBorrowerRecords(fspStaffUsers);        
        list<Loan__c> loanList = LWCTestUtility.getBorrowerLoans(borrowers);
        list<Account> fspAccounts = LWCTestUtility.getFSPAccounts();
        list<Repayment_Schedule__c> rsList = new list<Repayment_Schedule__c>();
        for(Loan__c l: loanList){
            Decimal amount = l.Loan_Principal_Disbursed__c/l.Loan_Term_Months__c;
            for(Integer j=1; j<=l.Loan_Term_Months__c; j++){
                Date dt = System.Today();
                if(j==1){
                    dt=dt.addDays(-20);
                }else if(j==2){
                    
                }else{
                    dt=dt.addDays(30);
                }
                Repayment_Schedule__c rs = LWCTestUtility.getRepaymentRecord(l.Id, amount, dt);
                rs.Loan_Repayment_Number__c=j;
                newLoanRecViewController.getRecordTypeId(l.Id);
                rsList.add(rs);
            }
        }
        insert rsList;
        
        
        
        loanList = LWCTestUtility.submitLoanforReview(loanList);
        loanList = LWCTestUtility.updateLoansToPublish(loanList);
        list<Contact> lenders = LWCTestUtility.getLenderContacts();
        
        Test.startTest();
        LWCUtility.getLenderTransaction(lenders[0], 'Loan', 35, loanList[0].Id, 'Held');
        LWCUtility.createChatterFeed_LoanRejection('', lenders[0].Id);
        LWCUtility.sendEmailToUsers(new set<String>{fspStaffUsers[0].Id});
        LWCUtility.increasePerformance();
        Test.stopTest();
    }
    
    public testmethod static void testGetAllActiveLenders(){
        Test.startTest();
        LWCUtility.getAllActiveLenders();
        LWCUtility.increasePerformance();
        Test.stopTest();
    }
    
    public testmethod static void testGetAllActiveFSPs(){
        Test.startTest();
        LWCUtility.getAllActiveFSPs();
        Test.stopTest();
    }
    
    public testmethod static void testexecuteOffsetCalculationManually(){
        Test.startTest();
        LWCUtility.executeOffsetCalculationManually();
        LWCUtility.increasePerformance();
        Test.stopTest();
    }
    
    public testmethod static void testCreateChatterFeed_LoanRepayment(){
        // Create a Chatter group
        CollaborationGroup cg = new CollaborationGroup(Name = 'LWC Admin1', CollaborationType = 'Private', Description = 'LWC Admin Chatter group', CanHaveGuests = false, IsArchived = false, IsAutoArchiveDisabled = true);
        insert cg;
        Test.startTest();
        LWCUtility.createChatterFeed_LoanRepayment(cg.Id, 'test', 'test');
        LWCUtility.increasePerformance();
        Test.stopTest();
    }
    
    public testmethod static void testupdateFXRatesManually(){
        Test.startTest();
        LWCUtility.updateFXRatesManually();
        LWCUtility.increasePerformance();
        Test.stopTest();
    }
    
    public testmethod static void testgetLWCAdminUsers(){
        Test.startTest();
        LWCUtility.getLWCAdminUsers();
        LWCUtility.increasePerformance();
        Test.stopTest();
    }
    
    public testmethod static void testgetFinanceTeamUsers(){
        Test.startTest();
        LWCUtility.getFinanceTeamUsers();
        LWCUtility.increasePerformance();
        Test.stopTest();
    }
    
    public testmethod static void testgetCommunityUser(){
        Test.startTest();
        LWCUtility.getCommunityUser();
        LWCUtility.increasePerformance();
        Test.stopTest();
    }
    
    public testmethod static void testgetMonth(){
        Test.startTest();
        LWCUtility.getMonth(LWCUtility.getMonth(1));
        LWCUtility.getMonth(LWCUtility.getMonth(2));
        LWCUtility.getMonth(LWCUtility.getMonth(3));
        LWCUtility.getMonth(LWCUtility.getMonth(4));
        LWCUtility.getMonth(LWCUtility.getMonth(5));
        LWCUtility.getMonth(LWCUtility.getMonth(6));
        LWCUtility.getMonth(LWCUtility.getMonth(7));
        LWCUtility.getMonth(LWCUtility.getMonth(8));
        LWCUtility.getMonth(LWCUtility.getMonth(9));
        LWCUtility.getMonth(LWCUtility.getMonth(10));
        LWCUtility.getMonth(LWCUtility.getMonth(11));
        LWCUtility.getMonth(LWCUtility.getMonth(12));
        LWCUtility.increasePerformance();
        Test.stopTest();
    }
    public testmethod static void testgetLoanReviwerIsManager(){
        // Create a test user
        User testUser = [select Id,Name from User where FirstName ='Test' AND LastName='User' limit 1];
        // Create a test queue
        Group testQueue = new Group(
            Name = 'Care Loan Managers',
            Type = 'Queue'
        );
        insert testQueue;

        // Create a test contact
        Contact testContact = new Contact(
            FirstName = 'John',
            LastName = 'Doe',
            Email = 'johndoe@example.com'
        );
        insert testContact;

        // Add the test contact to the test queue
        System.runAs(new User(Id = UserInfo.getUserId())) {
            GroupMember testQueueMember = new GroupMember(
                GroupId = testQueue.Id,
                UserOrGroupId = testUser.Id
                
            );
            insert testQueueMember;
        }
        
        Test.startTest();
        LWCUtility.checkIfLoanReviewerIsManager(testContact.Id);
        LWCUtility.increasePerformance();
        Test.stopTest();
    }
    
    public testmethod static void testAMLCheck()
    {
         //LWC_Config_Setting__mdt lwcGlobalSettings = LWC_Config_Setting__mdt.getInstance('LWC_Global');
         list<String> lenderIds = LWCTestUtility.getLenderUsersIds();
        Id customerRTId = LWCUtility.getCustomerRecordTypeId();
        //LWCTestUtility.getLenderContacts();
        //List<Contact> lenderContacts=[SELECT Id,Name,RecordTypeId FROM Contact WHERE RecordTypeId=:customerRTId] ;
       	List<User> lenderUser=[SELECT Id, Name,ContactId FROM User WHERE isActive=true AND Profile.Name='Lender' AND ContactId!=null LIMIT 2];
        List<Contact> lenderContacts=new List<Contact>();
        for(User u: lenderUser)
        	lenderContacts.add(new Contact(RecordTypeId=customerRTId, FirstName='Test1', LastName = 'Staff',IsLender__c=true,Active__c=true,
                                         Email='testLender@example.com',Id=u.ContactId));
        Database.DMLOptions dml = new Database.DMLOptions(); 
        dml.DuplicateRuleHeader.AllowSave = true;
        Database.SaveResult[] sr=Database.update(lenderContacts, dml);
        list<Loan__c> getloans= LWCTestUtility.getBorrowerLoans(LWCTestUtility.getBorrowerRecords(lenderUser));
        List<String> testLenderIds=new List<string>();
        for(Contact c: lenderContacts)
        	testLenderIds.add(c.Id);
        System.debug('lender Contacts from donate test-->'+lenderContacts);
        map<String, Lender_Balance__c> lenderBalanceMap = LWCTestUtility.getLenderBalances(lenderContacts);
        System.debug('Lender balance map-->'+lenderBalanceMap);
        
        Test.startTest();
        try{
            List<Transaction__c> transactions=LWCTestUtility.getLoanTransactionList(getloans,testLenderIds);
            List<Transaction__c> transactionsR=LWCTestUtility.getRepaymentTransactionList(getloans,testLenderIds);
            List<Transaction__c> updatetrans=new List<Transaction__c>();
            for(Transaction__c t: transactions)
                updatetrans.add(t);
            
            for(Transaction__c t: transactionsR)
                updatetrans.add(t);
            
            System.debug('Transactions list-->'+updatetrans);
            List<Repayment_Schedule__c> rslist=new List<Repayment_Schedule__c>();
            for(Loan__c l:getloans)
                rslist.add(new Repayment_Schedule__c(Loan__c=l.Id,Status__c=null,Repayment_Date__c=null,Amount_Due__c=1000000, Due_Date__c=Date.today()));
            insert rslist;
            
            System.debug('Repayments from AML Test-->'+rslist);
            
            LWC_AMLScreeningScheduler ctrl = new LWC_AMLScreeningScheduler();
            // Loan__c loan=[SELECT Id FROM Loan__c Limit 1];
            //ctrl.execute(null);
            String sch = '0 0 8 * * ?'; 
            system.schedule('LWC_DonateLenderBalanceInactiveLender', sch, ctrl);
        }catch(Exception e){}
        Test.stopTest();
        
    }
      
    
    
    
}