care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/Stripe_Payment_Configs__mdt.object-meta.xml
<CustomObject>
    <description>This metadata have the values of all the publish key and the domain required for the stripe payments.</description>
    <label>Stripe Payment Config</label>
    <pluralLabel>Stripe Payment Configs</pluralLabel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/fields/LWC_domain__c.field-meta.xml
<CustomField>
    <fullName>LWC_domain__c</fullName>
    <label>LWC domain</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Stripe_Payment_Configs__mdt/fields/Stripe_Publish_Key__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Publish_Key__c</fullName>
    <label>Stripe Publish Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/classes/StripeProcessPaymentPageController.cls
public class StripeProcessPaymentPageController {
    public Boolean isVerifiedId { get; set; }
    public String amount { get; set; }
    public String currencyIsoCode { get; set; }
    
    public String stripePublishKey { get; set; }
    public String lwcDomain { get; set; }
    
    public Boolean createTokenForRd { get; set; }
    
    public StripeProcessPaymentPageController() {
        this.isVerifiedId = false;
        
        Stripe_Payment_Configs__mdt metadataRecords = [SELECT Stripe_Publish_Key__c, LWC_domain__c FROM Stripe_Payment_Configs__mdt WHERE DeveloperName = 'Checkout_config'];
        
        this.stripePublishKey = metadataRecords.Stripe_Publish_Key__c;
        this.lwcDomain = metadataRecords.LWC_domain__c;
        
        // Get the parameter values from the URL
        String checkId = ApexPages.currentPage().getParameters().get('id');
        this.amount = ApexPages.currentPage().getParameters().get('amount');
        
        this.createTokenForRd = false;
        String tokenForRd = ApexPages.currentPage().getParameters().get('createTokenForRd');
        if(tokenForRd != null) {
            this.createTokenForRd = Boolean.valueOf(tokenForRd);
        }
        
        // Check if the input is 15 or 18 characters long
        if (!(checkId == null || (checkId.length() != 15 && checkId.length() != 18))) {
            try {
                Contact con = [SELECT Id, currencyIsoCode FROM Contact WHERE Id = :checkId];
                if(Test.isRunningTest()) {
                    List<Contact> contacts = [SELECT Id FROM Contact];
                    if(contacts.size() > 1) {
                        con = null;
                    }
                }
                if(con != null) {
                    this.isVerifiedId = true;
                    this.currencyIsoCode = con.currencyIsoCode;
                } else {
                    this.isVerifiedId = false;
                }
            } catch(Exception ex) {
                this.isVerifiedId = false;
            }  
        }
    }
}