care-australia-uat/force-app/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Cart__c/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <formula>IF(NOT(ISBLANK(Last_Transaction_DateTime__c)), IF(((NOW() - Last_Transaction_DateTime__c) * 24 * 60) &gt; 45, TRUE, FALSE), False)</formula>
    <label>Expired</label>
    <type>Checkbox</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Cart__c/fields/Last_Transaction_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Last_Transaction_DateTime__c</fullName>
    <label>Last Transaction DateTime</label>
    <type>DateTime</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Cart_Items__c/Cart_Items__c.object-meta.xml
<CustomObject>
    <label>Cart Items</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Cart Itens Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Cart_Items__c/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <label>Cart</label>
    <referenceTo>Cart__c</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Cart_Items__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Proposal_Status__c.field-meta.xml
<CustomField>
    <fullName>Loan_Proposal_Status__c</fullName>
    <label>Loan Proposal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>System Rejected</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Content Approved</fullName>
            </value>
            <value>
                <fullName>Ready to Publish</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <description>Used for Editable</description>
    <label>Loan</label>
</RecordType>

care-australia-uat/force-app/main/default/objects/LWC_Error_Log__c/LWC_Error_Log__c.object-meta.xml
<CustomObject>
    <label>LWC Error Log</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>LWC Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LWC Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Added_To_Cart__c.field-meta.xml
<CustomField>
    <fullName>Added_To_Cart__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Added To Cart</label>
    <type>Checkbox</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Cart_Items__c.field-meta.xml
<CustomField>
    <fullName>Cart_Items__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cart Items</label>
    <referenceTo>Cart_Items__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan the transaction relates to</description>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Held</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/classes/LWC_DataCleanUpScheduler.cls
/**
* Name			:		LWC_DataCleanUpScheduler
* Date			:		28/09/2023
* Author		:		Amit Goyal
* Description	:		To send the loan for manager approval if did not happen by automation
						To Release the loans from the lock in case kept in cart for long
*/
global class LWC_DataCleanUpScheduler Implements Database.Batchable<sObject>, Schedulable{
	global void execute(SchedulableContext sc)
    {
        LWC_DataCleanUpScheduler b = new LWC_DataCleanUpScheduler();
        database.executebatch(b, 100);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        DateTime dt = System.NOW().addMinutes(-60);
        String query = 'Select Id, Name, Expired__c, (Select Id, Name From Cart_Items__r) From Cart__c Where Last_Transaction_DateTime__c <=: dt';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Cart__c> carts) {
        SavePoint sp = Database.setSavepoint();
        System.debug('Carts---->'+carts);
        map<String, Cart_Items__c> cartItemsMap = new map<String, Cart_Items__c>();
        try {
            for(Cart__c c: carts){
                if(c.Expired__c==true){
                    if(c.Cart_Items__r != null && c.Cart_Items__r.size()>0){
                        cartItemsMap.putAll(c.Cart_Items__r);
                    }
                }
                c.Last_Transaction_DateTime__c=null;
            }
            
            list<Transaction__c> transactions = [Select Id, Name From Transaction__c Where Cart_Items__c IN: cartItemsMap.keyset() AND Added_To_Cart__c=true AND Status__c!='Completed'];
            
            update  carts;
            if(transactions != null && transactions.size()>0){
                delete transactions;
            }
            
            if(cartItemsMap != null && cartItemsMap.size()>0){
                delete cartItemsMap.values();
            }
            
            /*map<String, Cart_Items__c> recordsMap = new map<String, Cart_Items__c>([Select Id, Name From Cart_Items__c Where Cart__r.Expired__c=true]);
            system.debug('### recordsMap size: '+recordsMap.size());
            list<Transaction__c> records = [Select Id, Name From Transaction__c Where Cart_Items__c IN: recordsMap.keyset()];
            system.debug('### records size: '+records.size());
            delete recordsMap.values();*/
        } catch(Exception e) {
            system.debug('### exception: '+e+' - '+e.getStackTraceString());
            Database.rollback(sp);
            System.debug(e.getMessage());
            LWC_Error_Log__c err = new LWC_Error_Log__c(Class_Name__c='LWC_DataCleanUpScheduler', MethodName__c='execute', 
                                                        Exception_Type__c='Error', Description__c=e.getMessage(), 
                                                        StackTrace__c=e.getStackTraceString());
            insert err;
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        map<String, Loan__c> recordsMap = new map<String, Loan__c>([SElect Id, Name From Loan__c Where Loan_Proposal_Status__C='Content Approved']);
        LoanTriggerHandler.sendLoanforManagerApproval(recordsMap.keyset());
    }
}