care-australia-uat/force-app/main/default/objects/BamboraAPI__c/BamboraAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Bambora API</label>
</CustomObject>

care-australia-uat/force-app/main/default/objects/BamboraAPI__c/fields/Batch_API__c.field-meta.xml
<CustomField>
    <fullName>Batch_API__c</fullName>
    <label>Batch API</label>
    <type>Url</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/BamboraAPI__c/fields/Cash_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Cash_Account_Number__c</fullName>
    <label>Cash Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/BamboraAPI__c/fields/Merchant_ID__c.field-meta.xml
<CustomField>
    <fullName>Merchant_ID__c</fullName>
    <description>Custom Checkout Merchant ID/GUID</description>
    <label>Merchant ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/BamboraAPI__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>Password for RG Payments</description>
    <label>RG Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/BamboraAPI__c/fields/Payment_API__c.field-meta.xml
<CustomField>
    <fullName>Payment_API__c</fullName>
    <label>Payment API</label>
    <type>Url</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/BamboraAPI__c/fields/RG_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>RG_Account_Number__c</fullName>
    <label>RG Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/BamboraAPI__c/fields/TokeniseCC_API__c.field-meta.xml
<CustomField>
    <fullName>TokeniseCC_API__c</fullName>
    <label>TokeniseCC API</label>
    <type>Url</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/BamboraAPI__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Username for RG Payments</description>
    <label>RG Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/RG_Processing_Batch__c/RG_Processing_Batch__c.object-meta.xml
<CustomObject>
    <description>Processing recurring donation payment jobs.</description>
    <label>RG Processing Batch</label>
    <nameField>
        <displayFormat>RGP{0000000}</displayFormat>
        <label>RG Processing Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RG Processing Batchs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/RG_Processing_Batch__c/fields/Batch_Status__c.field-meta.xml
<CustomField>
    <fullName>Batch_Status__c</fullName>
    <label>Batch Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Fail Soft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/RG_Processing_Batch__c/fields/Batch_Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Batch_Unique_Identifier__c</fullName>
    <label>Batch Unique Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/RG_Processing_Batch__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/RG_Processing_Batch__c/fields/Status_Description__c.field-meta.xml
<CustomField>
    <fullName>Status_Description__c</fullName>
    <label>Status Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/RG_Processing_Batch__c/fields/Total_Transactions__c.field-meta.xml
<CustomField>
    <fullName>Total_Transactions__c</fullName>
    <label>Total Transactions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/classes/AuthorizePaymentBatch_Test.cls
@istest
public class AuthorizePaymentBatch_Test  {
    @testSetup 
    public static void setup() {
        BamboraAPI__c bamboraSettings = new BamboraAPI__c();
        bamboraSettings.Name = 'Bambora';
        bamboraSettings.Merchant_ID__c = 'test';
        bamboraSettings.Username__c = 'Test';
        bamboraSettings.Password__c = 'Test';
        bamboraSettings.Cash_Account_Number__c = 'Test';
        bamboraSettings.RG_Account_Number__c = 'Test';
        bamboraSettings.Batch_API__c = 'https://demo.ippayments.com.au/interface/api/batch.asmx';
        bamboraSettings.Payment_API__c = 'https://demo.ippayments.com.au/interface/api/dts.asmx';
        bamboraSettings.TokeniseCC_API__c = 'https://demo.ippayments.com.au/interface/api/sipp.asmx';
        insert bamboraSettings;

        
        RG_Processing_Batch__c rgProcessingBatch = new RG_Processing_Batch__c();
        rgProcessingBatch.Batch_Status__c = 'Submitted';
        rgProcessingBatch.Batch_Unique_Identifier__c = '123456';
        rgProcessingBatch.Scheduled_Date__c = Date.today();
        rgProcessingBatch.Payment_Method__c = 'Credit Card';
        rgProcessingBatch.Total_Transactions__c = 2;
        rgProcessingBatch.Total_Amount__c =3000;
        insert rgProcessingBatch;
        

    }
    @isTest 
    public static void testmethod_responce_0(){
		System.debug([SELECT Id, Batch_Unique_Identifier__c, Scheduled_Date__c, Payment_Method__c, Total_Transactions__c, 
                      Batch_Status__c, Total_Amount__c, Status_Description__c, Name FROM RG_Processing_Batch__c]);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new BamboraAuthoriseBatchTrnFileMock(200,0));
        AuthorizePaymentBatch apb = new AuthorizePaymentBatch();
        Database.executeBatch(apb);
        Test.stopTest();
    }
     @isTest 
    public static void testmethod_responce_1(){


        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new BamboraAuthoriseBatchTrnFileMock(200,1));
        AuthorizePaymentBatch apb = new AuthorizePaymentBatch();
        Database.executeBatch(apb);
        Test.stopTest();
    }
     @isTest 
    public static void testmethod_responce_2(){


        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new BamboraAuthoriseBatchTrnFileMock(200,2));
        AuthorizePaymentBatch apb = new AuthorizePaymentBatch();
        Database.executeBatch(apb);
        Test.stopTest();
    }
     @isTest 
    public static void testmethod_responce_3(){


        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new BamboraAuthoriseBatchTrnFileMock(200,3));
        AuthorizePaymentBatch apb = new AuthorizePaymentBatch();
        Database.executeBatch(apb);
        Test.stopTest();
    }
     @isTest 
    public static void testmethod_responce_4(){


        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new BamboraAuthoriseBatchTrnFileMock(200,4));
        AuthorizePaymentBatch apb = new AuthorizePaymentBatch();
        Database.executeBatch(apb);
        Test.stopTest();
    }
     @isTest 
    public static void testmethod_responce_5(){


        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new BamboraAuthoriseBatchTrnFileMock(200,5));
        AuthorizePaymentBatch apb = new AuthorizePaymentBatch();
        Database.executeBatch(apb);
        Test.stopTest();
    }
    @isTest 
    public static void testmethod_responce_99(){


        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new BamboraAuthoriseBatchTrnFileMock(200,99));
        AuthorizePaymentBatch apb = new AuthorizePaymentBatch();
        Database.executeBatch(apb);
        Test.stopTest();
    }
    @isTest 
    public static void testmethod_responce_ELSE(){


        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new BamboraAuthoriseBatchTrnFileMock(200,50));
        AuthorizePaymentBatch apb = new AuthorizePaymentBatch();
        Database.executeBatch(apb);
        Test.stopTest();
    }

}