care-australia-uat/force-app/main/default/objects/BamboraAPI__c/BamboraAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Bambora API</label>
</CustomObject>

care-australia-uat/force-app/main/default/objects/BamboraAPI__c/fields/Batch_API__c.field-meta.xml
<CustomField>
    <fullName>Batch_API__c</fullName>
    <label>Batch API</label>
    <type>Url</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/BamboraAPI__c/fields/Cash_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Cash_Account_Number__c</fullName>
    <label>Cash Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/BamboraAPI__c/fields/Cash_Password__c.field-meta.xml
<CustomField>
    <fullName>Cash_Password__c</fullName>
    <description>Password for Cash Payments</description>
    <label>Cash Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/BamboraAPI__c/fields/Cash_Username__c.field-meta.xml
<CustomField>
    <fullName>Cash_Username__c</fullName>
    <description>Username for Cash Payments</description>
    <label>Cash Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/BamboraAPI__c/fields/Merchant_ID__c.field-meta.xml
<CustomField>
    <fullName>Merchant_ID__c</fullName>
    <description>Custom Checkout Merchant ID/GUID</description>
    <label>Merchant ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/BamboraAPI__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>Password for RG Payments</description>
    <label>RG Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/BamboraAPI__c/fields/Payment_API__c.field-meta.xml
<CustomField>
    <fullName>Payment_API__c</fullName>
    <label>Payment API</label>
    <type>Url</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/BamboraAPI__c/fields/RG_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>RG_Account_Number__c</fullName>
    <label>RG Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/BamboraAPI__c/fields/TokeniseCC_API__c.field-meta.xml
<CustomField>
    <fullName>TokeniseCC_API__c</fullName>
    <label>TokeniseCC API</label>
    <type>Url</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/BamboraAPI__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Username for RG Payments</description>
    <label>RG Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/RG_Response__c/RG_Response__c.object-meta.xml
<CustomObject>
    <description>RG_Responses capture the bank response codes from Bambora for processing Regular Gifts</description>
    <label>RG Response</label>
    <nameField>
        <displayFormat>RGR{0000}</displayFormat>
        <label>RG Response Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RG Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/RG_Response__c/fields/Merchant_Category__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Category__c</fullName>
    <label>Merchant Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Merchant_Category</valueSetName>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/RG_Response__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Direct Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/RG_Response__c/fields/Payment_Result__c.field-meta.xml
<CustomField>
    <fullName>Payment_Result__c</fullName>
    <label>Payment Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Result</valueSetName>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/RG_Response__c/fields/Response_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Code__c</fullName>
    <label>Response Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/RG_Response__c/fields/Result_Description__c.field-meta.xml
<CustomField>
    <fullName>Result_Description__c</fullName>
    <label>Result Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/globalValueSets/Merchant_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Braintree</fullName>
    </customValue>
    <customValue>
        <fullName>PayPal</fullName>
    </customValue>
    <customValue>
        <fullName>Offline</fullName>
    </customValue>
    <customValue>
        <fullName>EverydayHero</fullName>
    </customValue>
    <customValue>
        <fullName>GiveEasy</fullName>
    </customValue>
    <customValue>
        <fullName>Cardly</fullName>
    </customValue>
    <customValue>
        <fullName>Good2Give</fullName>
    </customValue>
    <customValue>
        <fullName>Shopify</fullName>
    </customValue>
    <customValue>
        <fullName>Bambora</fullName>
    </customValue>
    <customValue>
        <fullName>Benevity</fullName>
    </customValue>
    <customValue>
        <fullName>General Community Fundraising</fullName>
    </customValue>
    <customValue>
        <fullName>GoFundraise</fullName>
    </customValue>
    <customValue>
        <fullName>Good Company</fullName>
    </customValue>
    <customValue>
        <fullName>Grassrootz</fullName>
    </customValue>
    <customValue>
        <fullName>MyCause</fullName>
    </customValue>
    <customValue>
        <fullName>PayPal Giving Fund</fullName>
    </customValue>
    <customValue>
        <fullName>Stripe</fullName>
    </customValue>
    <customValue>
        <fullName>Catalyser</fullName>
    </customValue>
    <customValue>
        <fullName>LWC Transaction</fullName>
    </customValue>
    <masterLabel>Merchant Category</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

care-australia-uat/force-app/main/default/globalValueSets/Payment_Result.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Processed</fullName>
        <default>true</default>
        <label>Not Processed</label>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Success</fullName>
    </customValue>
    <customValue>
        <fullName>Fail Hard</fullName>
    </customValue>
    <customValue>
        <fullName>Fail Soft</fullName>
    </customValue>
    <customValue>
        <fullName>ERROR</fullName>
    </customValue>
    <description>Payment Result Values for Payment Records</description>
    <masterLabel>Payment Result</masterLabel>
</GlobalValueSet>

care-australia-uat/force-app/main/default/classes/MakePaymentController_Test.cls
@istest
public class MakePaymentController_Test  {
    @testSetup 
    public static void setup() {
        
        BamboraAPI__c bamboraSettings = new BamboraAPI__c();
        bamboraSettings.Name = 'Bambora';
        bamboraSettings.Merchant_ID__c = 'test';
        bamboraSettings.Username__c = 'RG Test';
        bamboraSettings.Password__c = 'RG Test';
        bamboraSettings.Cash_Username__c = 'Cash Test';
        bamboraSettings.Cash_Password__c = 'Cah Test';
        bamboraSettings.Cash_Account_Number__c = 'Test';
        bamboraSettings.RG_Account_Number__c = 'Test';
        bamboraSettings.Batch_API__c = 'https://demo.ippayments.com.au/interface/api/batch.asmx';
        bamboraSettings.Payment_API__c = 'https://demo.ippayments.com.au/interface/api/dts.asmx';
        bamboraSettings.TokeniseCC_API__c = 'https://demo.ippayments.com.au/interface/api/sipp.asmx';
        insert bamboraSettings;
        
        
        
        Contact con = TestDataFactory.createContact(true);
        Campaign camp = TestDataFactory.createCampaign(true);
        npe03__Recurring_Donation__c rd = new npe03__Recurring_Donation__c();
        rd.npe03__Amount__c = 100;
        rd.npe03__Contact__c = con.Id;
        rd.npe03__Recurring_Donation_Campaign__c = camp.Id;
        rd.npsp__PaymentMethod__c = 'Credit Card';
        rd.npsp__Status__c = 'Active';
        insert rd;
        
      /* npe01__OppPayment__c payment = new npe01__OppPayment__c();
       payment.npe01__Payment_Amount__c = 100;
       inseRt payment;*/
        List<RG_Response__c> rgResponseList = new List<RG_Response__c>();
         RG_Response__c rgSuccessResponse = new RG_Response__c();
        rgSuccessResponse.Response_Code__c = '0' ;
        rgSuccessResponse.Result_Description__c = 'Approved' ;
        rgSuccessResponse.Payment_Result__c  = 'Success' ;
        rgSuccessResponse.Merchant_Category__c = 'Bambora' ;
        rgSuccessResponse.Payment_Method__c = 'Credit Card' ;
        rgResponseList.add(rgSuccessResponse);
        
        RG_Response__c rgFailHardResponse = new RG_Response__c();
        rgFailHardResponse.Response_Code__c = '12' ;
        rgFailHardResponse.Result_Description__c = 'Invalid Transaction' ;
        rgFailHardResponse.Payment_Result__c  = 'Fail Hard' ;
        rgFailHardResponse.Merchant_Category__c = 'Bambora' ;
        rgFailHardResponse.Payment_Method__c = 'Credit Card' ;
        rgResponseList.add(rgFailHardResponse);
        
         RG_Response__c rgERRORResponse = new RG_Response__c();
        rgERRORResponse.Response_Code__c = 'ERROR' ;
        rgERRORResponse.Result_Description__c = 'Unknown Error' ;
        rgERRORResponse.Payment_Result__c  = 'ERROR' ;
        rgERRORResponse.Merchant_Category__c = 'Bambora' ;
        rgERRORResponse.Payment_Method__c = 'Credit Card' ;
        rgResponseList.add(rgERRORResponse);
        
        insert rgResponseList;
    }
    
    @isTest 
    public static void testmethod1(){
        npe01__OppPayment__c payment = [SELECT Id, npe01__Payment_Amount__c FROM npe01__OppPayment__c limit 1];
        ApexPages.currentpage().getparameters().put('id' , payment.Id);
        
        Test.startTest();
        MakePaymentController makePayment = new MakePaymentController();
        makePayment.initVFP();
        MakePaymentController.getPaymentRecords(payment.Id);
        Test.stopTest();
        
    }
    /*@isTest 
    public static void testmethod2(){
        npe03__Recurring_Donation__c rd = [select Id from npe03__Recurring_Donation__c limit 1];
        PageReference reference = Page.RDTokenizationVisualforce;
        
        Test.startTest();
        Test.setCurrentPage(reference);
       	reference.getparameters().put('stt' ,'Test-Test');
        RDTokenizationController rdTokenization = new RDTokenizationController();
        rdTokenization.getCCToken();
        Test.stopTest();
    }*/
    @isTest 
    static void testCallout_responce_0() {
        // Set mock callout class 
       
        
        npe01__OppPayment__c payment = [SELECT Id, npe01__Payment_Amount__c FROM npe01__OppPayment__c limit 1];
         PageReference reference = Page.RDTokenizationVisualforce;
        Test.setCurrentPage(reference);
       	reference.getparameters().put('stt' ,'Test-Test');
        reference.getparameters().put('payeeName' ,'Test-payeeName');
         ApexPages.currentpage().getparameters().put('id' , payment.Id);
        // Call method to test.
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock.
         MakePaymentController makePayment = new MakePaymentController();
        Test.startTest();
        makePayment.initVFP();
        Test.setMock(HttpCalloutMock.class, new BamboraMakePaymentMock(200,0));
        makePayment.makePayment();
        Test.stopTest();
        
        
    }
    @isTest 
    static void testCallout_responce_500() {
        // Set mock callout class 
       
        
        npe01__OppPayment__c payment = [SELECT Id, npe01__Payment_Amount__c FROM npe01__OppPayment__c limit 1];
         PageReference reference = Page.RDTokenizationVisualforce;
        Test.setCurrentPage(reference);
       	reference.getparameters().put('stt' ,'Test-Test');
        reference.getparameters().put('payeeName' ,'Test-payeeName');
         ApexPages.currentpage().getparameters().put('id' , payment.Id);
        // Call method to test.
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock.
         MakePaymentController makePayment = new MakePaymentController();
        Test.startTest();
        makePayment.initVFP();
        Test.setMock(HttpCalloutMock.class, new BamboraMakePaymentMock(200,500));
        makePayment.makePayment();
        Test.stopTest();
        
        
    }

    @isTest 
    static void testCallout_responce_5068() {
        // Set mock callout class 
       
        
        npe01__OppPayment__c payment = [SELECT Id, npe01__Payment_Amount__c FROM npe01__OppPayment__c limit 1];
         PageReference reference = Page.RDTokenizationVisualforce;
        Test.setCurrentPage(reference);
       	reference.getparameters().put('stt' ,'Test-Test');
        reference.getparameters().put('payeeName' ,'Test-payeeName');
         ApexPages.currentpage().getparameters().put('id' , payment.Id);
        // Call method to test.
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock.
         MakePaymentController makePayment = new MakePaymentController();
        Test.startTest();
        makePayment.initVFP();
        Test.setMock(HttpCalloutMock.class, new BamboraMakePaymentMock(200,5068));
        makePayment.makePayment();
        Test.stopTest();
        
        
    }
}