care-australia-uat/force-app/main/default/objects/FSP_Monthly_Settlement__c/FSP_Monthly_Settlement__c.object-meta.xml
<CustomObject>
    <label>FSP Monthly Settlement</label>
    <nameField>
        <displayFormat>MS-{00000}</displayFormat>
        <label>FSP Monthly Settlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FSP Monthly Settlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/FSP_Monthly_Settlement__c/fields/FSP__c.field-meta.xml
<CustomField>
    <fullName>FSP__c</fullName>
    <label>FSP</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>FSP Monthly Settlements</relationshipLabel>
    <relationshipName>FSP_Monthly_Settlements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/FSP_Monthly_Settlement__c/fields/FSP_Staff__c.field-meta.xml
<CustomField>
    <fullName>FSP_Staff__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FSP Staff</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>FSP Monthly Settlements</relationshipLabel>
    <relationshipName>FSP_Monthly_Settlements</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/FSP_Monthly_Settlement__c/fields/Offset_Calculation_Date__c.field-meta.xml
<CustomField>
    <fullName>Offset_Calculation_Date__c</fullName>
    <label>Offset Calculation Date</label>
    <type>Date</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Actual_Loan_Principle_Disbursed_AUD__c.field-meta.xml
<CustomField>
    <fullName>Actual_Loan_Principle_Disbursed_AUD__c</fullName>
    <label>Actual Loan Principle Disbursed (AUD)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Buffer_To_Repay__c.field-meta.xml
<CustomField>
    <fullName>Buffer_To_Repay__c</fullName>
    <label>Buffer To Repay</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/FSP__c.field-meta.xml
<CustomField>
    <fullName>FSP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FSP</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/FSP_Monthly_Settlement__c.field-meta.xml
<CustomField>
    <fullName>FSP_Monthly_Settlement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FSP Monthly Settlement</label>
    <referenceTo>FSP_Monthly_Settlement__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Principal_Disbursed__c.field-meta.xml
<CustomField>
    <fullName>Loan_Principal_Disbursed__c</fullName>
    <description>Loan amount the borrower received in local currency</description>
    <label>Loan Principal Disbursed (LC)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Loan_Term_Months__c.field-meta.xml
<CustomField>
    <fullName>Loan_Term_Months__c</fullName>
    <description>&quot;number of month for borrower to repay
displayed as Loan length on website&quot;</description>
    <label>Number of Repayments</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Published_Amount_AUD__c.field-meta.xml
<CustomField>
    <fullName>Published_Amount_AUD__c</fullName>
    <description>Principal + buffer</description>
    <label>Loan Principal Published</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Repaid_Date__c.field-meta.xml
<CustomField>
    <fullName>Repaid_Date__c</fullName>
    <label>Repaid Date</label>
    <type>Date</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Fundraising</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Written off</fullName>
            </value>
            <value>
                <fullName>Repaid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Loan__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <description>Used for Editable</description>
    <label>Loan</label>
</RecordType>

care-australia-uat/force-app/main/default/objects/LWC_Config_Setting__mdt/LWC_Config_Setting__mdt.object-meta.xml
<CustomObject>
    <label>LWC Config Setting</label>
    <pluralLabel>LWC Config Settings</pluralLabel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/LWC_Config_Setting__mdt/fields/Campaign_AutoRelendDonation__c.field-meta.xml
<CustomField>
    <fullName>Campaign_AutoRelendDonation__c</fullName>
    <label>Campaign_AutoRelendDonation</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/LWC_Config_Setting__mdt/fields/Campaign_BalanceDonation__c.field-meta.xml
<CustomField>
    <fullName>Campaign_BalanceDonation__c</fullName>
    <label>Campaign_BalanceDonation</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/LWC_Config_Setting__mdt/fields/Campaign_GeneralDonation__c.field-meta.xml
<CustomField>
    <fullName>Campaign_GeneralDonation__c</fullName>
    <label>Campaign_GeneralDonation</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Repayment Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Amount_Due__c.field-meta.xml
<CustomField>
    <fullName>Amount_Due__c</fullName>
    <label>Amount Due</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/FSP_Monthly_Settlement__c.field-meta.xml
<CustomField>
    <fullName>FSP_Monthly_Settlement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FSP Monthly Settlement</label>
    <referenceTo>FSP_Monthly_Settlement__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <label>Care Loan ID</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Loan_Repayment_Number__c.field-meta.xml
<CustomField>
    <fullName>Loan_Repayment_Number__c</fullName>
    <label>Loan Repayment Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Non_performing_loan_options__c.field-meta.xml
<CustomField>
    <fullName>Non_performing_loan_options__c</fullName>
    <description>list of options for FSP to select if loan is underpaid, this then gets communicated to the lenders for that loan.</description>
    <label>Non-performing loan options</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Loss of income</fullName>
            </value>
            <value>
                <fullName>Personal or family issues</fullName>
            </value>
            <value>
                <fullName>Natural disaster</fullName>
            </value>
            <value>
                <fullName>Unable to reach borrower (MFI issue)</fullName>
            </value>
            <value>
                <fullName>Comment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Non_performing_loan_options_other__c.field-meta.xml
<CustomField>
    <fullName>Non_performing_loan_options_other__c</fullName>
    <label>Non-performing loan options other</label>
    <type>TextArea</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Principal_Repaid__c.field-meta.xml
<CustomField>
    <fullName>Principal_Repaid__c</fullName>
    <description>Amount paid off during reporting month (principal)</description>
    <label>Principal Repaid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Underpaid</fullName>
            </value>
            <value>
                <fullName>Overpaid</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <label>Repaid</label>
            </value>
            <value>
                <fullName>Written off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Repayment_Schedule__c/fields/Write_Off_Request__c.field-meta.xml
<CustomField>
    <fullName>Write_Off_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Write Off Request</label>
    <type>Checkbox</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Lender__c.field-meta.xml
<CustomField>
    <fullName>Lender__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Unique ID</description>
    <label>Lender</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.RecordType.Name</field>
            <operation>equals</operation>
            <value>Supporter</value>
        </filterItems>
        <filterItems>
            <field>Contact.IsLender__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Loan the transaction relates to</description>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Held</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Topup</fullName>
            </value>
            <value>
                <fullName>Repayment</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
                <label>Withdrawal / Refund</label>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
            <value>
                <fullName>Donation</fullName>
            </value>
            <value>
                <fullName>FX Gain</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Expired Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

care-australia-uat/force-app/main/default/classes/LWCLenderRepaymentSchedulerTest.cls
@isTest
public class LWCLenderRepaymentSchedulerTest {
    @TestSetup
    private static void testData(){
        list<CollaborationGroup> cgList = LWCTestUtility.createCollaborationGroups(true);
        
        LWC_Config_Setting__mdt lwcGlobalSettings = LWC_Config_Setting__mdt.getInstance('LWC_Global');
        list<Campaign> parentCampaignList = new list<Campaign>();
        parentCampaignList.add(new Campaign(Name='Donation', IsActive=true, Campaign_Code__c=lwcGlobalSettings.Campaign_GeneralDonation__c));
        parentCampaignList.add(new Campaign(Name='LenderBalance', IsActive=true, Campaign_Code__c=lwcGlobalSettings.Campaign_BalanceDonation__c));
        parentCampaignList.add(new Campaign(Name='AutoRelend', IsActive=true, Campaign_Code__c=lwcGlobalSettings.Campaign_AutoRelendDonation__c));
        insert parentCampaignList;
        
        List<Product2> products = new List<Product2>();
        products.add(new Product2(Name='Donation', IsActive=true, CurrencyIsoCode='AUD'));
        insert products;
        
        List<PricebookEntry> bookEntries = new List<PricebookEntry>();
        for(Product2 prod: products) {
         	bookEntries.add(new PricebookEntry(UnitPrice=1, Product2Id=prod.Id, Pricebook2Id=Test.getStandardPricebookId(), IsActive=true));   
        }
        insert bookEntries;
        
        list<User> fspStaffUsers = LWCTestUtility.getFSPStaffUsers();
        list<Contact> borrowers = LWCTestUtility.getBorrowerRecords(fspStaffUsers);        
        list<Loan__c> loanList = LWCTestUtility.getBorrowerLoans(borrowers);
        list<Account> fspAccounts = LWCTestUtility.getFSPAccounts();
        system.debug('### fspAccounts size(): '+fspAccounts.size());
        list<Repayment_Schedule__c> rsList = new list<Repayment_Schedule__c>();
        for(Loan__c l: loanList){
            Decimal amount = l.Loan_Principal_Disbursed__c/l.Loan_Term_Months__c;
            for(Integer j=1; j<=l.Loan_Term_Months__c; j++){
                Date dt = System.Today();
                if(j==1){
                    dt=dt.addDays(-20);
                }else if(j==2){
                    
                }else{
                    dt=dt.addDays(30);
                }
                Repayment_Schedule__c rs = LWCTestUtility.getRepaymentRecord(l.Id, amount, dt);
                rs.Loan_Repayment_Number__c=j;
                rsList.add(rs);
            }
        }
        insert rsList;

        loanList = LWCTestUtility.submitLoanforReview(loanList);
        loanList = LWCTestUtility.updateLoansToPublish(loanList);
        
        String customerRTId=LWCUtility.getCustomerRecordTypeId();
        List<Contact> lenderContacts = new List<Contact>();
        set<Id> lIds = new set<Id>();
        System.debug('::'+LWCUtility.getAllActiveLenders().size());
        Contact l1 = new Contact(RecordTypeId=customerRTId, FirstName='Test1', LastName = 'Staff', Street__c='Test', Ward__c='Test', 
                                    District__c='Test', City__c='Test', Country__c='Vietnam', Email='test11@example.com', IsLender__c=true
                                  );
        //for(user u : [SELECT ContactId FROM User WHERE Profile.Name = 'Lender' AND ContactId !=null LIMIT 1]){
        //    l1.Id = u.ContactId;
        //}
        insert l1;
        Contact lwcGuest = new Contact(RecordTypeId=customerRTId, FirstName='LWC Guest', LastName = 'Lender', IsLender__c=true);
        insert lwcGuest;
        
        Contact fxGain = new Contact(RecordTypeId=customerRTId, FirstName='LWC FX', LastName = 'Lender', IsLender__c=true);
        insert fxGain;
        list<String> lenderIds = new list<String>();
        list<Transaction__c> transactionList = new list<Transaction__c>();
        for(Loan__c l: loanList){
            system.debug('### Published_Amount_AUD__c: '+l.Published_Amount_AUD__c);
            transactionList.add(new Transaction__c(Loan__c=l.Id, Lender__c=l1.Id, Type__c='Loan', Amount__c=25, Status__c='Completed'));
            transactionList.add(new Transaction__c(Loan__c=l.Id, Lender__c=l1.Id, Type__c='Repayment', Amount__c=25, Status__c='Completed'));
            transactionList.add(new Transaction__c(Loan__c=l.Id, Lender__c=lwcGuest.Id, Type__c='Loan', Amount__c=25, Status__c='Completed'));
            l.Stage__c='Active';
            l.Actual_Loan_Principle_Disbursed_AUD__c=1500;
            l.Buffer_To_Repay__c=38.54;
            //l.Repaid_Date__c = Date.today();
        }
        insert transactionList;
        update loanList;
        
        Integer month=System.Today().addMonths(-1).Month();
        Integer year=System.Today().addMonths(-1).Year();
        
        // Get the first day of the month
        Date firstDayOfMonth = Date.newInstance(year, month, 1);
        // Get the last day of the month
        Integer lastDayOfMonth = Date.daysInMonth(year, month);
        Date lastDayDate = Date.newInstance(year, month, lastDayOfMonth);
        
        list<Repayment_Schedule__c> rsToSetPayments = [Select Id, Name, Amount_Due__c, Due_Date__c
                                                       From Repayment_Schedule__c 
                                                       Where Due_Date__c >=: firstDayOfMonth AND Due_Date__c <=: lastDayDate];
        //system.debug('### rsToSetPayments Size: '+rsToSetPayments.size());
        Integer m=1;
        for(Repayment_Schedule__c rs: rsToSetPayments){
            rs.Repayment_Date__c=System.Today();
            if(m<3){
                rs.Principal_Repaid__c=rs.Amount_Due__c;
                rs.Repayment_Date__c=System.Today();
                rs.Status__c='Paid';
            }else if(m>=3 && m<6){
                if(m!=4){
                    rs.Principal_Repaid__c=rs.Amount_Due__c/2;
                    rs.Repayment_Date__c=System.Today();
                    rs.Status__c='Underpaid';
                    rs.Non_performing_loan_options__c='Loss of income';
                    rs.Non_performing_loan_options_other__c='test';
                }
            }else if(m>=6 && m<9){
                rs.Principal_Repaid__c=0;
                rs.Repayment_Date__c=System.Today();
                rs.Status__c='Skipped';
                rs.Non_performing_loan_options__c='Loss of income';
                rs.Non_performing_loan_options_other__c='test';
            }else{
                rs.Principal_Repaid__c=0;
                rs.Repayment_Date__c=System.Today();
                rs.Status__c='Skipped';
                rs.Non_performing_loan_options__c='Loss of income';
                rs.Non_performing_loan_options_other__c='test';
                rs.Write_Off_Request__c=true;
                rs.Comments__c='test';
            }
            m++;
        }
        update rsList;
        
        list<FSP_Monthly_Settlement__c> fmsList = new list<FSP_Monthly_Settlement__c>();
        String monthYear=LWCUtility.getMonth(month)+'-'+year;
        for(User usr: fspStaffUsers){
            fmsList.add(new FSP_Monthly_Settlement__c(FSP__c=fspAccounts[0].Id, FSP_Staff__c=usr.ContactId,
                                                      Offset_Calculation_Date__c=System.Today().addMonths(-1), Month__c=month, 
                                                      Year__c=year, Offset_Month_Year__c=monthYear, Offset_Balance_for_FSP_USD__c=20,
                                                      Below_Threshold__c=true, Offset_Clearance__c=false));
        }
        insert fmsList;
    }
    
    public testmethod static void testLWCLenderRepaymentScheduler(){
        LWCLenderRepaymentScheduler ctrl = new LWCLenderRepaymentScheduler();
        Date firstDayOfThisMonth = Date.newInstance(System.today().year(), System.today().month(), 1);
        Integer lastDayOfThisMonth = Date.daysInMonth(System.today().year(), System.today().month());
        Date lastDayDateOfThisMonth = Date.newInstance(System.today().year(), System.today().month(), lastDayOfThisMonth);
        System.debug( 'F:'+firstDayOfThisMonth );
        System.debug( 'L:'+lastDayDateOfThisMonth );
        List<Repayment_Schedule__c> rSchs = [SELECT Name, Principal_Repaid__c, Repayment_Date__c, Status__c FROM Repayment_Schedule__c];
        for( Repayment_Schedule__c rSch: rSchs ){
            rSch.Principal_Repaid__c = 5;
            rSch.Status__c = 'Underpaid';
        }
        UPDATE rSchs;
        System.debug('recsss:'+[SELECT Name, Principal_Repaid__c, Repayment_Date__c, Status__c FROM Repayment_Schedule__c]);
        Test.startTest();
        String sch = '0 0 23 * * ?'; 
        system.schedule('LWCLenderRepayment', sch, ctrl);
        Test.stopTest();
    }
    
    public testmethod static void testLWCLenderRepaymentBatchScheduler(){
        List<Repayment_Schedule__c> rSchs = [SELECT Name, Principal_Repaid__c, Repayment_Date__c, Status__c FROM Repayment_Schedule__c];
        for( Repayment_Schedule__c rSch: rSchs ){
            rSch.Status__c = 'Underpaid';
        }
        UPDATE rSchs;
        Test.startTest();
        LWCLenderRepaymentScheduler uprb = new LWCLenderRepaymentScheduler();
        Database.executeBatch(uprb,50);
        Test.stopTest();
    }
}