care-australia-uat/force-app/main/default/objects/ApexDebugLog__c/ApexDebugLog__c.object-meta.xml
<CustomObject>
    <label>Apex Debug Log</label>
    <nameField>
        <displayFormat>ADL{000000000}</displayFormat>
        <label>Apex Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

care-australia-uat/force-app/main/default/objects/ApexDebugLog__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

care-australia-uat/force-app/main/default/objects/ApexDebugLog__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>Stack Trace</label>
    <type>TextArea</type>
</CustomField>

care-australia-uat/force-app/main/default/classes/ApexLogCreator.cls
/**
 * Class Name: ApexLogCreator
 * Auhtor: Gerent Team
 * Description: create a log in case of error genetation
 * Modification Details: Deepesh Bansal - 08/09/2022 - Initial version created
 * */

public class ApexLogCreator {
    // insert the error record in ApexDebugLog__c
    public static void createApexLog(String className, String errorMessage,String method, String stackTrace){
        // instace of ApexDebugLog__c
        ApexDebugLog__c log = new ApexDebugLog__c();
        log.ApexClass__c = className;
        if(errorMessage.length() < 131072){
        	log.Message__c = errorMessage;    
        }
        else{
            log.Message__c = errorMessage.substring(0, 131071);
        }
        log.Method__c = method;
        if(stackTrace.length() < 255){
        	log.StackTrace__c = stackTrace;    
        }
        else{
            log.StackTrace__c = stackTrace.substring(0, 254);
        }
        // insert the error record
        insert log;
    }
}